import type { PermissionKey } from "@hotelos/shared";
import { assertPermissions } from "@hotelos/shared";
import { ForbiddenError } from "../lib/http-error.js";

// Audit 2026-06 · #3: dedupe log of GET routes hitting the fail-open path, so
// manifest gaps are auditable in the logs. Logged once per path to avoid spam.
const loggedUnmappedGets = new Set<string>();

export type ApiRoutePermission = {
  method: "GET" | "POST" | "PATCH" | "DELETE";
  path: string;
  permissions: PermissionKey[];
  riskLevel: "public" | "low" | "medium" | "high" | "critical";
};

export const routePermissionManifest: ApiRoutePermission[] = [
  { method: "GET", path: "/health", permissions: [], riskLevel: "public" },
  { method: "GET", path: "/metrics", permissions: ["audit.read"], riskLevel: "low" },
  { method: "POST", path: "/auth/login", permissions: [], riskLevel: "public" },
  { method: "POST", path: "/auth/forgot-password", permissions: [], riskLevel: "public" },
  { method: "POST", path: "/auth/reset-password", permissions: [], riskLevel: "public" },
  { method: "POST", path: "/auth/change-password", permissions: [], riskLevel: "low" },
  { method: "GET", path: "/auth/password-policy", permissions: [], riskLevel: "public" },
  // Bootstrap del piloto: público (gated por BOOTSTRAP_TOKEN + first-run check)
  { method: "GET", path: "/onboarding/bootstrap/status", permissions: [], riskLevel: "public" },
  { method: "POST", path: "/onboarding/bootstrap", permissions: [], riskLevel: "public" },
  { method: "POST", path: "/users", permissions: ["users.invite"], riskLevel: "high" },
  { method: "POST", path: "/auth/register-device", permissions: [], riskLevel: "low" },
  { method: "GET", path: "/auth/sessions", permissions: [], riskLevel: "low" },
  { method: "POST", path: "/auth/sessions/:id/revoke", permissions: [], riskLevel: "medium" },
  { method: "POST", path: "/auth/mfa/challenge", permissions: [], riskLevel: "medium" },
  { method: "POST", path: "/auth/mfa/verify", permissions: [], riskLevel: "medium" },
  { method: "GET", path: "/users/me/properties", permissions: [], riskLevel: "low" },
  { method: "GET", path: "/users/me/preferences", permissions: [], riskLevel: "low" },
  { method: "PATCH", path: "/users/me/preferences", permissions: [], riskLevel: "low" },
  { method: "GET", path: "/properties", permissions: [], riskLevel: "low" },
  { method: "GET", path: "/search", permissions: [], riskLevel: "low" },
  { method: "GET", path: "/webhooks/event-types", permissions: [], riskLevel: "low" },
  { method: "GET", path: "/webhooks/subscriptions", permissions: ["developer.manage_webhooks"], riskLevel: "medium" },
  { method: "POST", path: "/webhooks/subscriptions", permissions: ["developer.manage_webhooks"], riskLevel: "high" },
  { method: "PATCH", path: "/webhooks/subscriptions/:id", permissions: ["developer.manage_webhooks"], riskLevel: "high" },
  { method: "DELETE", path: "/webhooks/subscriptions/:id", permissions: ["developer.manage_webhooks"], riskLevel: "high" },
  { method: "GET", path: "/webhooks/subscriptions/:id/deliveries", permissions: ["developer.manage_webhooks"], riskLevel: "medium" },
  { method: "POST", path: "/webhooks/subscriptions/:id/test", permissions: ["developer.manage_webhooks"], riskLevel: "medium" },
  { method: "GET", path: "/assistant/tools", permissions: [], riskLevel: "low" },
  { method: "POST", path: "/assistant/chat", permissions: [], riskLevel: "low" },
  { method: "GET", path: "/tourist-tax/rates", permissions: ["folio.charge.post"], riskLevel: "low" },
  { method: "POST", path: "/tourist-tax/rates", permissions: ["compliance.configure"], riskLevel: "high" },
  { method: "POST", path: "/tourist-tax/seed", permissions: ["compliance.configure"], riskLevel: "medium" },
  { method: "POST", path: "/tourist-tax/compute", permissions: [], riskLevel: "low" },
  { method: "POST", path: "/tourist-tax/apply", permissions: ["folio.charge.post"], riskLevel: "high" },
  { method: "GET", path: "/properties/:propertyId/tourist-tax/applications", permissions: ["folio.charge.post"], riskLevel: "medium" },
  { method: "POST", path: "/reservations/:id/wallet-pass", permissions: ["pms.checkin.execute"], riskLevel: "high" },
  { method: "POST", path: "/mobile-keys/:serial/verify", permissions: [], riskLevel: "medium" },
  { method: "POST", path: "/mobile-keys/:serial/revoke", permissions: ["pms.checkin.execute"], riskLevel: "high" },
  { method: "GET", path: "/tbai/territories", permissions: [], riskLevel: "low" },
  { method: "POST", path: "/invoices/:id/tbai/submit", permissions: ["compliance.configure"], riskLevel: "high" },
  { method: "GET", path: "/properties/:propertyId/tbai/chain/:territory/verify", permissions: ["compliance.configure"], riskLevel: "medium" },
  { method: "GET", path: "/properties/:propertyId/tbai/submissions", permissions: ["compliance.configure"], riskLevel: "medium" },
  { method: "POST", path: "/properties/:propertyId/banking/csb43/import", permissions: ["accounting.journal.post"], riskLevel: "high" },
  { method: "POST", path: "/banking/sepa/remittances", permissions: ["accounting.journal.post"], riskLevel: "high" },
  { method: "POST", path: "/banking/iban/validate", permissions: [], riskLevel: "low" },
  { method: "GET", path: "/esrs/catalog", permissions: [], riskLevel: "low" },
  { method: "GET", path: "/organizations/:orgId/esrs/:year/indicators", permissions: ["compliance.configure"], riskLevel: "medium" },
  { method: "POST", path: "/esrs/indicators", permissions: ["compliance.configure"], riskLevel: "high" },
  { method: "POST", path: "/organizations/:orgId/esrs/:year/generate", permissions: ["compliance.configure"], riskLevel: "high" },
  { method: "GET", path: "/organizations/:orgId/esrs/:year/report", permissions: ["compliance.configure"], riskLevel: "medium" },
  { method: "GET", path: "/marketplace/categories", permissions: [], riskLevel: "low" },
  { method: "GET", path: "/marketplace/listings", permissions: [], riskLevel: "low" },
  { method: "GET", path: "/marketplace/listings/:appId", permissions: [], riskLevel: "low" },
  { method: "POST", path: "/marketplace/listings", permissions: ["developer.manage_webhooks"], riskLevel: "high" },
  { method: "POST", path: "/marketplace/listings/:appId/install", permissions: [], riskLevel: "medium" },
  { method: "POST", path: "/marketplace/listings/:appId/uninstall", permissions: [], riskLevel: "medium" },
  { method: "GET", path: "/marketplace/installations", permissions: [], riskLevel: "low" },
  { method: "GET", path: "/developer/apps", permissions: ["developer.manage_webhooks"], riskLevel: "medium" },
  { method: "POST", path: "/developer/apps", permissions: ["developer.manage_webhooks"], riskLevel: "high" },
  { method: "POST", path: "/developer/apps/:appId/rotate-secret", permissions: ["developer.manage_webhooks"], riskLevel: "high" },
  { method: "GET", path: "/oauth/scopes", permissions: [], riskLevel: "low" },
  { method: "POST", path: "/oauth/authorize", permissions: [], riskLevel: "high" },
  { method: "POST", path: "/oauth/token", permissions: [], riskLevel: "high" },
  { method: "GET", path: "/notifications", permissions: [], riskLevel: "low" },
  { method: "POST", path: "/notifications/:id/read", permissions: [], riskLevel: "low" },
  { method: "GET", path: "/settings/security", permissions: [], riskLevel: "low" },
  { method: "POST", path: "/onboarding/projects", permissions: ["onboarding.create"], riskLevel: "high" },
  { method: "GET", path: "/onboarding/projects", permissions: ["onboarding.read"], riskLevel: "medium" },
  { method: "GET", path: "/onboarding/projects/:projectId", permissions: ["onboarding.read"], riskLevel: "medium" },
  { method: "PATCH", path: "/onboarding/projects/:projectId", permissions: ["onboarding.create"], riskLevel: "high" },
  { method: "POST", path: "/onboarding/projects/:projectId/source-connections", permissions: ["onboarding.connect_source"], riskLevel: "high" },
  { method: "POST", path: "/onboarding/source-connections/:connectionId/test", permissions: ["onboarding.connect_source"], riskLevel: "medium" },
  { method: "POST", path: "/onboarding/source-connections/:connectionId/sync", permissions: ["onboarding.connect_source"], riskLevel: "high" },
  { method: "POST", path: "/onboarding/projects/:projectId/files", permissions: ["onboarding.upload"], riskLevel: "high" },
  { method: "GET", path: "/onboarding/projects/:projectId/files", permissions: ["onboarding.read"], riskLevel: "medium" },
  { method: "POST", path: "/onboarding/files/:fileId/classify", permissions: ["onboarding.ai_extract"], riskLevel: "medium" },
  { method: "POST", path: "/onboarding/files/:fileId/extract", permissions: ["onboarding.ai_extract"], riskLevel: "high" },
  { method: "POST", path: "/onboarding/projects/:projectId/ai/analyze", permissions: ["onboarding.ai_extract"], riskLevel: "high" },
  { method: "POST", path: "/onboarding/projects/:projectId/ai/generate-blueprint", permissions: ["onboarding.ai_map"], riskLevel: "high" },
  { method: "POST", path: "/onboarding/projects/:projectId/ai/generate-mappings", permissions: ["onboarding.ai_map"], riskLevel: "high" },
  { method: "POST", path: "/onboarding/projects/:projectId/room-walk/parse", permissions: ["onboarding.ai_map"], riskLevel: "high" },
  { method: "POST", path: "/onboarding/files/:fileId/floor-plan/map", permissions: ["onboarding.ai_map"], riskLevel: "high" },
  { method: "POST", path: "/onboarding/projects/:projectId/ai/data-quality", permissions: ["onboarding.review"], riskLevel: "high" },
  { method: "GET", path: "/onboarding/projects/:projectId/extracted-entities", permissions: ["onboarding.read"], riskLevel: "medium" },
  { method: "GET", path: "/onboarding/projects/:projectId/mapping-suggestions", permissions: ["onboarding.read"], riskLevel: "medium" },
  { method: "GET", path: "/onboarding/projects/:projectId/human-review-queue", permissions: ["onboarding.review"], riskLevel: "high" },
  { method: "PATCH", path: "/onboarding/mapping-suggestions/:suggestionId/approve", permissions: ["onboarding.review"], riskLevel: "high" },
  { method: "PATCH", path: "/onboarding/mapping-suggestions/:suggestionId/reject", permissions: ["onboarding.review"], riskLevel: "medium" },
  { method: "PATCH", path: "/onboarding/mapping-suggestions/:suggestionId/edit", permissions: ["onboarding.review"], riskLevel: "high" },
  { method: "POST", path: "/onboarding/projects/:projectId/dry-run", permissions: ["onboarding.apply"], riskLevel: "high" },
  { method: "GET", path: "/onboarding/projects/:projectId/dry-run-result", permissions: ["onboarding.read"], riskLevel: "medium" },
  { method: "POST", path: "/onboarding/projects/:projectId/apply", permissions: ["onboarding.apply"], riskLevel: "critical" },
  { method: "POST", path: "/onboarding/projects/:projectId/rollback", permissions: ["onboarding.rollback"], riskLevel: "critical" },
  { method: "GET", path: "/onboarding/projects/:projectId/readiness", permissions: ["onboarding.read"], riskLevel: "medium" },
  { method: "GET", path: "/onboarding/projects/:projectId/cutover-plan", permissions: ["onboarding.read"], riskLevel: "medium" },
  { method: "POST", path: "/onboarding/projects/:projectId/cutover/delta-import/dry-run", permissions: ["onboarding.manage_cutover"], riskLevel: "critical" },
  { method: "POST", path: "/onboarding/projects/:projectId/go-live", permissions: ["onboarding.go_live"], riskLevel: "critical" },
  { method: "GET", path: "/revenue/properties/:propertyId/dashboard", permissions: ["revenue.read"], riskLevel: "medium" },
  { method: "GET", path: "/revenue/properties/:propertyId/metrics", permissions: ["revenue.read"], riskLevel: "medium" },
  { method: "GET", path: "/revenue/properties/:propertyId/history-forecast", permissions: ["revenue.history_forecast.read"], riskLevel: "medium" },
  { method: "GET", path: "/revenue/properties/:propertyId/history-forecast/report", permissions: ["revenue.history_forecast.read"], riskLevel: "medium" },
  { method: "GET", path: "/revenue/properties/:propertyId/history-forecast/charts", permissions: ["revenue.history_forecast.read"], riskLevel: "medium" },
  { method: "GET", path: "/revenue/properties/:propertyId/history-forecast/kpis", permissions: ["revenue.history_forecast.read"], riskLevel: "medium" },
  { method: "POST", path: "/revenue/properties/:propertyId/history-forecast/export", permissions: ["revenue.history_forecast.export"], riskLevel: "high" },
  {
    method: "POST",
    path: "/revenue/properties/:propertyId/history-forecast/saved-views",
    permissions: ["revenue.history_forecast.saved_views.manage"],
    riskLevel: "medium"
  },
  { method: "GET", path: "/revenue/properties/:propertyId/pickup", permissions: ["revenue.read"], riskLevel: "medium" },
  { method: "GET", path: "/revenue/properties/:propertyId/pace", permissions: ["revenue.read"], riskLevel: "medium" },
  { method: "POST", path: "/revenue/properties/:propertyId/pace/capture", permissions: ["revenue.recommend"], riskLevel: "medium" },
  { method: "GET", path: "/revenue/properties/:propertyId/forecast", permissions: ["revenue.forecast.read"], riskLevel: "medium" },
  { method: "GET", path: "/revenue/properties/:propertyId/forecasts", permissions: ["revenue.forecast.read"], riskLevel: "medium" },
  { method: "POST", path: "/revenue/properties/:propertyId/forecasts/generate", permissions: ["revenue.recommend"], riskLevel: "high" },
  { method: "GET", path: "/revenue/properties/:propertyId/forecasts/by-segment", permissions: ["revenue.forecast.read"], riskLevel: "medium" },
  { method: "GET", path: "/revenue/properties/:propertyId/forecasts/:date", permissions: ["revenue.forecast.read"], riskLevel: "medium" },
  { method: "GET", path: "/revenue/properties/:propertyId/forecast-accuracy", permissions: ["revenue.forecast.read"], riskLevel: "medium" },
  { method: "GET", path: "/revenue/properties/:propertyId/recommendations", permissions: ["revenue.read"], riskLevel: "medium" },
  { method: "POST", path: "/revenue/properties/:propertyId/recommendations/generate", permissions: ["revenue.recommend"], riskLevel: "high" },
  { method: "POST", path: "/revenue/properties/:propertyId/recommendations/:id/approve", permissions: ["revenue.apply_recommendations"], riskLevel: "critical" },
  { method: "POST", path: "/revenue/properties/:propertyId/recommendations/:id/apply", permissions: ["revenue.apply_recommendations"], riskLevel: "critical" },
  { method: "POST", path: "/revenue/properties/:propertyId/recommendations/:id/reject", permissions: ["revenue.apply_recommendations"], riskLevel: "high" },
  { method: "POST", path: "/revenue/recommendations/:recommendationId/approve", permissions: ["revenue.apply_recommendations"], riskLevel: "critical" },
  { method: "POST", path: "/revenue/recommendations/:recommendationId/apply", permissions: ["revenue.apply_recommendations"], riskLevel: "critical" },
  { method: "POST", path: "/revenue/recommendations/:recommendationId/reject", permissions: ["revenue.apply_recommendations"], riskLevel: "high" },
  { method: "POST", path: "/revenue/properties/:propertyId/pricing-rules", permissions: ["revenue.configure"], riskLevel: "high" },
  { method: "PATCH", path: "/revenue/pricing-rules/:id", permissions: ["revenue.configure"], riskLevel: "high" },
  { method: "POST", path: "/revenue/properties/:propertyId/bar-levels", permissions: ["revenue.configure"], riskLevel: "medium" },
  { method: "POST", path: "/revenue/properties/:propertyId/budget", permissions: ["revenue.configure"], riskLevel: "medium" },
  { method: "POST", path: "/revenue/properties/:propertyId/market-segments", permissions: ["revenue.configure"], riskLevel: "medium" },
  { method: "POST", path: "/revenue/properties/:propertyId/market-segments/seed", permissions: ["revenue.configure"], riskLevel: "medium" },
  { method: "POST", path: "/revenue/properties/:propertyId/displacement", permissions: ["revenue.read"], riskLevel: "low" },
  { method: "POST", path: "/properties/:propertyId/email/connections", permissions: ["integrations.connect"], riskLevel: "high" },
  { method: "DELETE", path: "/email/connections/:id", permissions: ["integrations.disconnect"], riskLevel: "medium" },
  { method: "POST", path: "/email/connections/:id/poll", permissions: ["integrations.connect"], riskLevel: "medium" },
  { method: "POST", path: "/properties/:propertyId/email/ingest", permissions: ["integrations.connect"], riskLevel: "medium" },
  { method: "POST", path: "/email/inbound/:id/approve", permissions: ["pms.reservation.create"], riskLevel: "high" },
  { method: "POST", path: "/email/inbound/:id/reject", permissions: ["integrations.connect"], riskLevel: "low" },
  { method: "GET", path: "/revenue/properties/:propertyId/channel-profitability", permissions: ["revenue.read"], riskLevel: "medium" },
  { method: "GET", path: "/revenue/properties/:propertyId/rate-grid", permissions: ["revenue.read"], riskLevel: "medium" },
  { method: "PATCH", path: "/revenue/properties/:propertyId/rate-grid/rates", permissions: ["revenue.manage_rates"], riskLevel: "critical" },
  { method: "PATCH", path: "/revenue/properties/:propertyId/rate-grid/restrictions", permissions: ["revenue.manage_restrictions"], riskLevel: "critical" },
  { method: "PATCH", path: "/revenue/properties/:propertyId/rate-grid/inventory", permissions: ["revenue.manage_rates"], riskLevel: "high" },
  { method: "POST", path: "/revenue/properties/:propertyId/rate-grid/bulk-update", permissions: ["revenue.manage_rates", "revenue.manage_restrictions"], riskLevel: "critical" },
  { method: "GET", path: "/revenue/properties/:propertyId/demand-calendar", permissions: ["revenue.forecast.read"], riskLevel: "medium" },
  { method: "POST", path: "/revenue/properties/:propertyId/demand-calendar", permissions: ["revenue.recommend"], riskLevel: "medium" },
  { method: "PATCH", path: "/revenue/demand-calendar/:eventId", permissions: ["revenue.recommend"], riskLevel: "medium" },
  { method: "DELETE", path: "/revenue/demand-calendar/:eventId", permissions: ["revenue.recommend"], riskLevel: "high" },
  { method: "POST", path: "/revenue/properties/:propertyId/scenarios/simulate", permissions: ["revenue.recommend"], riskLevel: "high" },
  { method: "GET", path: "/revenue/properties/:propertyId/scenarios", permissions: ["revenue.read"], riskLevel: "medium" },
  { method: "GET", path: "/revenue/scenarios/:scenarioId", permissions: ["revenue.read"], riskLevel: "medium" },
  { method: "GET", path: "/revenue/properties/:propertyId/automation-rules", permissions: ["revenue.automation.manage"], riskLevel: "high" },
  { method: "POST", path: "/revenue/properties/:propertyId/automation-rules", permissions: ["revenue.automation.manage"], riskLevel: "critical" },
  { method: "PATCH", path: "/revenue/automation-rules/:ruleId", permissions: ["revenue.automation.manage"], riskLevel: "critical" },
  { method: "POST", path: "/revenue/automation-rules/:ruleId/enable", permissions: ["revenue.automation.manage"], riskLevel: "critical" },
  { method: "POST", path: "/revenue/automation-rules/:ruleId/disable", permissions: ["revenue.automation.manage"], riskLevel: "critical" },
  { method: "GET", path: "/channel-manager/properties/:propertyId/channels", permissions: ["channel_manager.read"], riskLevel: "medium" },
  { method: "POST", path: "/channel-manager/properties/:propertyId/channels", permissions: ["channel_manager.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/channel-manager/channels/:channelId", permissions: ["channel_manager.manage"], riskLevel: "high" },
  { method: "POST", path: "/channel-manager/channels/:channelId/test", permissions: ["channel_manager.sync"], riskLevel: "medium" },
  { method: "GET", path: "/channel-manager/channels/:channelId/room-mappings", permissions: ["channel_manager.read"], riskLevel: "medium" },
  { method: "POST", path: "/channel-manager/channels/:channelId/room-mappings", permissions: ["channel_manager.mappings.manage"], riskLevel: "high" },
  { method: "GET", path: "/channel-manager/channels/:channelId/rate-mappings", permissions: ["channel_manager.read"], riskLevel: "medium" },
  { method: "POST", path: "/channel-manager/channels/:channelId/rate-mappings", permissions: ["channel_manager.mappings.manage"], riskLevel: "high" },
  { method: "POST", path: "/channel-manager/channels/:channelId/sync/availability", permissions: ["channel_manager.sync"], riskLevel: "critical" },
  { method: "POST", path: "/channel-manager/channels/:channelId/sync/rates", permissions: ["channel_manager.sync"], riskLevel: "critical" },
  { method: "POST", path: "/channel-manager/channels/:channelId/sync/restrictions", permissions: ["channel_manager.sync"], riskLevel: "critical" },
  { method: "POST", path: "/channel-manager/channels/:channelId/sync/full", permissions: ["channel_manager.sync"], riskLevel: "critical" },
  { method: "GET", path: "/channel-manager/channels/:channelId/sync-jobs", permissions: ["channel_manager.read"], riskLevel: "medium" },
  { method: "GET", path: "/channel-manager/properties/:propertyId/sync-health", permissions: ["channel_manager.read"], riskLevel: "medium" },
  { method: "POST", path: "/channel-manager/channels/:channelId/reservations/import", permissions: ["channel_manager.sync"], riskLevel: "high" },
  { method: "POST", path: "/channel-manager/channels/:channelId/webhook", permissions: ["channel_manager.sync"], riskLevel: "high" },
  { method: "GET", path: "/channel-manager/properties/:propertyId/external-reservations", permissions: ["channel_manager.read"], riskLevel: "medium" },
  // SiteMinder-style OTA aggregator (Sprint 28 — channel manager aggregator)
  { method: "GET", path: "/channel-manager/channels", permissions: ["channel_manager.read"], riskLevel: "medium" },
  { method: "POST", path: "/channel-manager/channels", permissions: ["channel_manager.manage"], riskLevel: "high" },
  { method: "POST", path: "/channel-manager/channels/:channelId/ingest", permissions: ["channel_manager.sync"], riskLevel: "medium" },
  { method: "POST", path: "/channel-manager/push-rates", permissions: ["channel_manager.sync"], riskLevel: "medium" },
  { method: "POST", path: "/channel-manager/push-availability", permissions: ["channel_manager.sync"], riskLevel: "medium" },
  { method: "POST", path: "/channel-manager/push-restrictions", permissions: ["channel_manager.sync"], riskLevel: "medium" },
  { method: "POST", path: "/channel-manager/ingest-all", permissions: ["channel_manager.sync"], riskLevel: "medium" },
  { method: "GET", path: "/channel-manager/sync-jobs", permissions: ["channel_manager.read"], riskLevel: "medium" },
  { method: "POST", path: "/channel-manager/parity/check", permissions: ["channel_manager.sync"], riskLevel: "medium" },
  { method: "GET", path: "/channel-manager/parity/alerts", permissions: ["channel_manager.parity.read"], riskLevel: "medium" },
  { method: "POST", path: "/channel-manager/parity/alerts/:id/resolve", permissions: ["channel_manager.manage"], riskLevel: "medium" },
  // Mapping management, readiness checklist + sandbox round-trip (Sprint 44)
  { method: "DELETE", path: "/channel-manager/room-mappings/:id", permissions: ["channel_manager.mappings.manage"], riskLevel: "high" },
  { method: "DELETE", path: "/channel-manager/rate-mappings/:id", permissions: ["channel_manager.mappings.manage"], riskLevel: "high" },
  { method: "GET", path: "/channel-manager/channels/:channelId/mapping-coverage", permissions: ["channel_manager.read"], riskLevel: "medium" },
  { method: "GET", path: "/channel-manager/channels/:channelId/readiness", permissions: ["channel_manager.read"], riskLevel: "medium" },
  { method: "POST", path: "/channel-manager/_sandbox/:provider", permissions: [], riskLevel: "public" },
  { method: "GET", path: "/rate-shopper/properties/:propertyId/competitors", permissions: ["revenue.read"], riskLevel: "medium" },
  { method: "POST", path: "/rate-shopper/properties/:propertyId/competitors", permissions: ["revenue.configure"], riskLevel: "high" },
  { method: "GET", path: "/rate-shopper/properties/:propertyId/rates", permissions: ["revenue.read"], riskLevel: "medium" },
  { method: "POST", path: "/rate-shopper/properties/:propertyId/shop", permissions: ["revenue.recommend"], riskLevel: "high" },
  { method: "GET", path: "/rate-shopper/properties/:propertyId/parity-alerts", permissions: ["revenue.read"], riskLevel: "medium" },
  { method: "POST", path: "/crm/profiles/:id/merge", permissions: ["crm.manage_profiles"], riskLevel: "high" },
  { method: "POST", path: "/crm/segments", permissions: ["crm.manage_profiles"], riskLevel: "medium" },
  { method: "PATCH", path: "/crm/segments/:id", permissions: ["crm.manage_profiles"], riskLevel: "medium" },
  { method: "POST", path: "/crm/campaigns", permissions: ["crm.manage_campaigns"], riskLevel: "high" },
  { method: "PATCH", path: "/crm/campaigns/:id", permissions: ["crm.manage_campaigns"], riskLevel: "high" },
  { method: "POST", path: "/crm/loyalty/programs", permissions: ["crm.manage_loyalty"], riskLevel: "high" },
  { method: "PATCH", path: "/crm/loyalty/memberships/:id", permissions: ["crm.manage_loyalty"], riskLevel: "high" },
  { method: "POST", path: "/sales/accounts", permissions: ["sales.pipeline.manage"], riskLevel: "medium" },
  { method: "POST", path: "/sales/opportunities", permissions: ["sales.pipeline.manage"], riskLevel: "medium" },
  { method: "PATCH", path: "/sales/opportunities/:id", permissions: ["sales.pipeline.manage"], riskLevel: "medium" },
  { method: "POST", path: "/groups/properties/:propertyId", permissions: ["groups.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/groups/:id", permissions: ["groups.manage"], riskLevel: "high" },
  { method: "POST", path: "/groups/:id/room-blocks", permissions: ["groups.block_inventory"], riskLevel: "critical" },
  { method: "POST", path: "/groups/:id/room-blocks/bulk", permissions: ["groups.manage"], riskLevel: "low" },
  { method: "POST", path: "/groups/:id/events", permissions: ["events.manage"], riskLevel: "high" },
  { method: "POST", path: "/groups/:id/rooming-list/import", permissions: ["groups.manage"], riskLevel: "medium" },
  { method: "GET", path: "/properties/:propertyId/event-spaces", permissions: ["events.read"], riskLevel: "low" },
  { method: "POST", path: "/groups/:id/release-unsold", permissions: ["groups.block_inventory"], riskLevel: "critical" },
  { method: "POST", path: "/groups/:id/master-folio", permissions: ["groups.manage"], riskLevel: "medium" },
  { method: "POST", path: "/groups/:id/create-reservations", permissions: ["groups.manage"], riskLevel: "critical" },
  { method: "POST", path: "/properties/:propertyId/groups/release-expired", permissions: ["groups.manage"], riskLevel: "medium" },
  { method: "POST", path: "/events/properties/:propertyId/spaces", permissions: ["events.manage_spaces"], riskLevel: "high" },
  { method: "POST", path: "/events/properties/:propertyId/events", permissions: ["events.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/events/:id", permissions: ["events.manage"], riskLevel: "high" },
  { method: "POST", path: "/events/:id/generate-beo", permissions: ["events.manage"], riskLevel: "high" },
  { method: "POST", path: "/workforce/properties/:propertyId/shifts", permissions: ["workforce.schedule.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/workforce/shifts/:id", permissions: ["workforce.schedule.manage"], riskLevel: "high" },
  { method: "POST", path: "/workforce/time-clock/clock-in", permissions: ["workforce.timeclock.use"], riskLevel: "medium" },
  { method: "POST", path: "/workforce/time-clock/clock-out", permissions: ["workforce.timeclock.use"], riskLevel: "medium" },
  { method: "POST", path: "/workforce/absences", permissions: ["workforce.schedule.manage"], riskLevel: "medium" },
  { method: "PATCH", path: "/workforce/absences/:id", permissions: ["workforce.schedule.manage"], riskLevel: "high" },
  { method: "POST", path: "/procurement/suppliers", permissions: ["procurement.manage"], riskLevel: "medium" },
  { method: "POST", path: "/inventory/properties/:propertyId/items", permissions: ["inventory.manage"], riskLevel: "medium" },
  { method: "POST", path: "/inventory/properties/:propertyId/stock-movements", permissions: ["inventory.adjust"], riskLevel: "high" },
  { method: "POST", path: "/inventory/properties/:propertyId/stock-counts", permissions: ["inventory.stock_count"], riskLevel: "high" },
  { method: "POST", path: "/procurement/properties/:propertyId/purchase-orders", permissions: ["purchase_orders.create"], riskLevel: "high" },
  { method: "POST", path: "/procurement/purchase-orders/:id/approve", permissions: ["purchase_orders.approve"], riskLevel: "critical" },
  { method: "POST", path: "/procurement/purchase-orders/:id/receive", permissions: ["purchase_orders.receive"], riskLevel: "high" },
  { method: "POST", path: "/guest-portal/session/:token/check-in", permissions: ["guest_self_service.manage"], riskLevel: "high" },
  { method: "POST", path: "/guest-portal/session/:token/check-out", permissions: ["guest_self_service.manage"], riskLevel: "high" },
  { method: "POST", path: "/guest-portal/session/:token/pay", permissions: ["guest_self_service.manage"], riskLevel: "critical" },
  { method: "POST", path: "/guest-portal/session/:token/invoice-request", permissions: ["guest_self_service.manage"], riskLevel: "high" },
  { method: "POST", path: "/guest-portal/session/:token/upsells/:offerId/purchase", permissions: ["guest_self_service.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/guest-self-service/properties/:propertyId/settings", permissions: ["guest_portal.configure"], riskLevel: "high" },
  // Guest portal real auth + pre-check-in + service requests (Sprint 40).
  // These are GUEST-scoped, not staff-permission-gated: the guest token IS the
  // auth. Registered as "public" with empty permissions (like /auth/login) so
  // the staff permission preHandler passes; each handler calls verifyGuestToken
  // itself and returns 401 when the token is invalid/expired.
  { method: "POST", path: "/guest-portal/sign-in", permissions: [], riskLevel: "public" },
  { method: "POST", path: "/guest-portal/sign-out", permissions: [], riskLevel: "public" },
  { method: "GET", path: "/guest-portal/reservation", permissions: [], riskLevel: "public" },
  { method: "POST", path: "/guest-portal/pre-check-in", permissions: [], riskLevel: "public" },
  { method: "POST", path: "/guest-portal/service-request", permissions: [], riskLevel: "public" },
  { method: "POST", path: "/reputation/reviews/:id/ai-draft-response", permissions: ["reputation.respond"], riskLevel: "medium" },
  { method: "POST", path: "/reputation/reviews/:id/respond", permissions: ["reputation.respond"], riskLevel: "high" },
  { method: "POST", path: "/quality/properties/:propertyId/cases", permissions: ["quality_cases.manage"], riskLevel: "medium" },
  { method: "PATCH", path: "/quality/cases/:id", permissions: ["quality_cases.manage"], riskLevel: "medium" },
  { method: "POST", path: "/surveys/properties/:propertyId", permissions: ["surveys.manage"], riskLevel: "medium" },
  { method: "POST", path: "/surveys/:id/responses", permissions: ["surveys.read"], riskLevel: "low" },
  { method: "POST", path: "/energy/properties/:propertyId/meters", permissions: ["energy.manage"], riskLevel: "medium" },
  { method: "POST", path: "/energy/properties/:propertyId/readings", permissions: ["energy.manage"], riskLevel: "medium" },
  { method: "POST", path: "/sustainability/properties/:propertyId/actions", permissions: ["sustainability.report"], riskLevel: "medium" },
  { method: "POST", path: "/safety/properties/:propertyId/incidents", permissions: ["incidents.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/safety/incidents/:id", permissions: ["incidents.manage"], riskLevel: "high" },
  { method: "POST", path: "/safety/incidents/:id/evidence", permissions: ["incidents.manage"], riskLevel: "high" },
  { method: "POST", path: "/safety/properties/:propertyId/checks", permissions: ["safety_checks.manage"], riskLevel: "high" },
  { method: "POST", path: "/safety/checks/:id/results", permissions: ["safety_checks.manage"], riskLevel: "medium" },
  { method: "POST", path: "/analytics/metrics", permissions: ["metrics.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/analytics/anomalies/:id", permissions: ["analytics.configure"], riskLevel: "medium" },
  { method: "POST", path: "/analytics/properties/:propertyId/reports", permissions: ["analytics.configure"], riskLevel: "medium" },
  { method: "POST", path: "/analytics/query", permissions: ["analytics.ai_ask"], riskLevel: "low" },
  { method: "POST", path: "/developer/apps", permissions: ["developer.manage_apps"], riskLevel: "high" },
  { method: "PATCH", path: "/developer/apps/:id", permissions: ["developer.manage_apps"], riskLevel: "high" },
  { method: "POST", path: "/developer/apps/:id/rotate-secret", permissions: ["developer.manage_apps"], riskLevel: "critical" },
  { method: "POST", path: "/developer/webhooks", permissions: ["developer.manage_webhooks"], riskLevel: "high" },
  { method: "PATCH", path: "/developer/webhooks/:id", permissions: ["developer.manage_webhooks"], riskLevel: "high" },
  { method: "POST", path: "/developer/webhooks/:id/test", permissions: ["developer.manage_webhooks"], riskLevel: "medium" },
  { method: "POST", path: "/ai-governance/policies", permissions: ["ai_governance.configure"], riskLevel: "high" },
  { method: "PATCH", path: "/ai-governance/policies/:id", permissions: ["ai_governance.configure"], riskLevel: "high" },
  { method: "PATCH", path: "/ai-governance/tools/:toolName", permissions: ["ai_tool_registry.manage"], riskLevel: "critical" },
  { method: "POST", path: "/ai-governance/prompts", permissions: ["ai_prompts.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/ai-governance/prompts/:id", permissions: ["ai_prompts.manage"], riskLevel: "high" },
  { method: "POST", path: "/ai-governance/evaluations/:id/run", permissions: ["ai_evals.manage"], riskLevel: "high" },
  { method: "POST", path: "/ai-governance/incidents", permissions: ["ai_incidents.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/ai-governance/incidents/:id", permissions: ["ai_incidents.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/ai-governance/human-review/:id", permissions: ["ai_governance.configure"], riskLevel: "high" },
  // AI Operations — pipeline status (Sprint 48, tool-call telemetry)
  { method: "GET", path: "/ai-operations/pipeline/dashboard", permissions: ["ai_governance.read"], riskLevel: "low" },
  { method: "GET", path: "/ai-operations/pipeline/calls/:id", permissions: ["ai_governance.read"], riskLevel: "low" },
  // AI Operations — Tool Registry (Sprint 47): catalog + per-property enablement.
  // Reads: ai_governance.read; writes: ai_tool_registry.manage (closest existing key to ai_governance.manage).
  { method: "POST", path: "/ai-operations/tools/sync", permissions: ["ai_tool_registry.manage"], riskLevel: "high" },
  { method: "GET", path: "/ai-operations/tools", permissions: ["ai_governance.read"], riskLevel: "low" },
  { method: "GET", path: "/ai-operations/tools/stats", permissions: ["ai_governance.read"], riskLevel: "low" },
  { method: "GET", path: "/ai-operations/tools/property-settings", permissions: ["ai_governance.read"], riskLevel: "low" },
  { method: "POST", path: "/ai-operations/tools/property-settings", permissions: ["ai_tool_registry.manage"], riskLevel: "high" },
  { method: "GET", path: "/ai-operations/tools/:toolName", permissions: ["ai_governance.read"], riskLevel: "low" },
  // AI Operations — per-property AI settings (Sprint 51): master switch + defaults.
  // Reads: ai_governance.read; writes: ai.high_risk.confirm (no ai_governance.manage perm exists).
  { method: "GET", path: "/ai-operations/property/settings", permissions: ["ai_governance.read"], riskLevel: "low" },
  { method: "POST", path: "/ai-operations/property/settings", permissions: ["ai.high_risk.confirm"], riskLevel: "high" },
  { method: "GET", path: "/ai-operations/property/readiness", permissions: ["ai_governance.read"], riskLevel: "low" },
  { method: "GET", path: "/ai-operations/property/configured", permissions: ["ai_governance.read"], riskLevel: "low" },
  // AI Operations — Governance center (Sprint 49): policies, prompts, evals, incidents, cost.
  // Reads: ai_governance.read / analytics.read; writes: ai_governance.configure; higher-risk
  // operations (publish prompt, run/create eval, incident mutations) use the dedicated perms.
  { method: "GET", path: "/ai-operations/governance/policies", permissions: ["ai_governance.read"], riskLevel: "medium" },
  { method: "POST", path: "/ai-operations/governance/policies", permissions: ["ai_governance.configure"], riskLevel: "high" },
  { method: "POST", path: "/ai-operations/governance/policies/:id/active", permissions: ["ai_governance.configure"], riskLevel: "high" },
  { method: "GET", path: "/ai-operations/governance/prompts", permissions: ["ai_governance.read"], riskLevel: "medium" },
  { method: "GET", path: "/ai-operations/governance/prompts/:promptCode/versions", permissions: ["ai_governance.read"], riskLevel: "medium" },
  { method: "GET", path: "/ai-operations/governance/prompts/diff", permissions: ["ai_governance.read"], riskLevel: "medium" },
  { method: "POST", path: "/ai-operations/governance/prompts/versions", permissions: ["ai_prompts.manage"], riskLevel: "high" },
  { method: "POST", path: "/ai-operations/governance/prompts/versions/:id/publish", permissions: ["ai_prompts.manage"], riskLevel: "critical" },
  { method: "POST", path: "/ai-operations/governance/prompts/versions/:id/archive", permissions: ["ai_prompts.manage"], riskLevel: "high" },
  { method: "GET", path: "/ai-operations/governance/evaluations", permissions: ["ai_governance.read"], riskLevel: "medium" },
  { method: "POST", path: "/ai-operations/governance/evaluations", permissions: ["ai_evals.manage"], riskLevel: "high" },
  { method: "POST", path: "/ai-operations/governance/evaluations/:id/run", permissions: ["ai_evals.manage"], riskLevel: "high" },
  { method: "GET", path: "/ai-operations/governance/incidents", permissions: ["ai_incidents.read"], riskLevel: "medium" },
  { method: "POST", path: "/ai-operations/governance/incidents", permissions: ["ai_incidents.manage"], riskLevel: "high" },
  { method: "POST", path: "/ai-operations/governance/incidents/:id/assign", permissions: ["ai_incidents.manage"], riskLevel: "high" },
  { method: "POST", path: "/ai-operations/governance/incidents/:id/resolve", permissions: ["ai_incidents.manage"], riskLevel: "high" },
  { method: "POST", path: "/ai-operations/governance/incidents/:id/reopen", permissions: ["ai_incidents.manage"], riskLevel: "high" },
  { method: "GET", path: "/ai-operations/governance/cost", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "GET", path: "/backoffice/properties/:propertyId/dashboard", permissions: ["backoffice.access"], riskLevel: "medium" },
  { method: "GET", path: "/backoffice/properties/:propertyId/configuration", permissions: ["configuration.read"], riskLevel: "medium" },
  { method: "GET", path: "/backoffice/properties/:propertyId/configuration/categories", permissions: ["categories.read"], riskLevel: "medium" },
  { method: "GET", path: "/backoffice/properties/:propertyId/configuration/categories/:categoryCode", permissions: ["categories.read"], riskLevel: "medium" },
  { method: "POST", path: "/backoffice/properties/:propertyId/configuration/categories/:categoryCode/options", permissions: ["categories.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/backoffice/properties/:propertyId/configuration/category-options/:optionId", permissions: ["categories.manage"], riskLevel: "high" },
  { method: "POST", path: "/backoffice/properties/:propertyId/configuration/category-options/:optionId/deactivate", permissions: ["categories.manage"], riskLevel: "high" },
  { method: "POST", path: "/backoffice/properties/:propertyId/configuration/category-options/:optionId/reactivate", permissions: ["categories.manage"], riskLevel: "high" },
  { method: "POST", path: "/backoffice/properties/:propertyId/configuration/categories/:categoryCode/reorder", permissions: ["categories.manage"], riskLevel: "high" },
  { method: "GET", path: "/backoffice/properties/:propertyId/configuration/custom-fields", permissions: ["custom_fields.read"], riskLevel: "medium" },
  { method: "POST", path: "/backoffice/properties/:propertyId/configuration/custom-fields", permissions: ["custom_fields.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/backoffice/properties/:propertyId/configuration/custom-fields/:fieldId", permissions: ["custom_fields.manage"], riskLevel: "high" },
  { method: "POST", path: "/backoffice/properties/:propertyId/configuration/custom-fields/:fieldId/deactivate", permissions: ["custom_fields.manage"], riskLevel: "high" },
  { method: "GET", path: "/backoffice/properties/:propertyId/configuration/entity/:entityType/:entityId/custom-fields", permissions: ["custom_fields.read"], riskLevel: "medium" },
  { method: "PATCH", path: "/backoffice/properties/:propertyId/configuration/entity/:entityType/:entityId/custom-fields", permissions: ["custom_fields.manage"], riskLevel: "high" },
  { method: "POST", path: "/backoffice/properties/:propertyId/configuration/categories/seed-defaults", permissions: ["categories.manage"], riskLevel: "high" },
  { method: "POST", path: "/backoffice/properties/:propertyId/configuration/categories/import", permissions: ["categories.import"], riskLevel: "critical" },
  { method: "POST", path: "/backoffice/properties/:propertyId/configuration/categories/export", permissions: ["categories.export"], riskLevel: "high" },
  { method: "GET", path: "/backoffice/configuration/category-templates", permissions: ["categories.read"], riskLevel: "medium" },
  { method: "POST", path: "/backoffice/properties/:propertyId/configuration/category-templates/:templateCode/apply-preview", permissions: ["categories.manage"], riskLevel: "high" },
  { method: "POST", path: "/backoffice/properties/:propertyId/configuration/category-templates/:templateCode/apply", permissions: ["categories.manage"], riskLevel: "critical" },
  { method: "POST", path: "/backoffice/properties/:propertyId/configuration/ai/suggest-categories", permissions: ["ai_category_setup.use"], riskLevel: "high" },
  { method: "GET", path: "/backoffice/properties/:propertyId/setup", permissions: ["backoffice.access"], riskLevel: "medium" },
  { method: "GET", path: "/backoffice/properties/:propertyId/manual-setup/options", permissions: ["configuration.read"], riskLevel: "medium" },
  { method: "GET", path: "/backoffice/properties/:propertyId/manual-setup/:optionCode", permissions: ["configuration.read"], riskLevel: "medium" },
  { method: "POST", path: "/backoffice/properties/:propertyId/manual-setup/:optionCode", permissions: ["configuration.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/backoffice/properties/:propertyId/manual-setup/:optionCode", permissions: ["configuration.manage"], riskLevel: "high" },
  { method: "GET", path: "/backoffice/properties/:propertyId/property-setup/forms", permissions: ["configuration.read"], riskLevel: "medium" },
  { method: "GET", path: "/backoffice/properties/:propertyId/property-setup/forms/:formCode", permissions: ["configuration.read"], riskLevel: "medium" },
  { method: "POST", path: "/backoffice/properties/:propertyId/property-setup/forms/:formCode", permissions: ["property.configure"], riskLevel: "high" },
  { method: "PATCH", path: "/backoffice/properties/:propertyId/property-setup/forms/:formCode", permissions: ["property.configure"], riskLevel: "high" },
  { method: "PATCH", path: "/backoffice/properties/:propertyId/setup/:stepCode", permissions: ["property.configure"], riskLevel: "high" },
  { method: "GET", path: "/backoffice/properties/:propertyId/readiness", permissions: ["backoffice.access"], riskLevel: "medium" },
  {
    method: "POST",
    path: "/backoffice/properties/:propertyId/readiness/recalculate",
    permissions: ["property.configure"],
    riskLevel: "high"
  },
  { method: "POST", path: "/backoffice/properties/:propertyId/go-live", permissions: ["property.go_live"], riskLevel: "critical" },
  { method: "GET", path: "/backoffice/properties/:propertyId/map", permissions: ["property.map.read"], riskLevel: "medium" },
  { method: "POST", path: "/backoffice/properties/:propertyId/buildings", permissions: ["property.map.manage"], riskLevel: "high" },
  { method: "POST", path: "/backoffice/properties/:propertyId/floors", permissions: ["property.map.manage"], riskLevel: "high" },
  { method: "POST", path: "/backoffice/properties/:propertyId/zones", permissions: ["property.map.manage"], riskLevel: "high" },
  { method: "POST", path: "/backoffice/properties/:propertyId/spaces", permissions: ["property.map.manage"], riskLevel: "high" },
  { method: "POST", path: "/backoffice/properties/:propertyId/map-positions", permissions: ["property.map.manage"], riskLevel: "high" },
  { method: "POST", path: "/backoffice/properties/:propertyId/rooms/bulk", permissions: ["property.map.manage"], riskLevel: "critical" },
  { method: "PATCH", path: "/backoffice/properties/:propertyId/rooms/bulk", permissions: ["property.map.manage"], riskLevel: "critical" },
  { method: "GET", path: "/backoffice/properties/:propertyId/property-map/export", permissions: ["property.map.read"], riskLevel: "medium" },
  { method: "GET", path: "/backoffice/properties/:propertyId/room-types", permissions: ["property.map.read"], riskLevel: "medium" },
  { method: "POST", path: "/backoffice/properties/:propertyId/room-types", permissions: ["property.map.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/backoffice/properties/:propertyId/room-types/:roomTypeId", permissions: ["property.map.manage"], riskLevel: "high" },
  {
    method: "POST",
    path: "/backoffice/properties/:propertyId/room-types/:roomTypeId/deactivate",
    permissions: ["property.map.manage"],
    riskLevel: "high"
  },
  {
    method: "POST",
    path: "/backoffice/properties/:propertyId/room-types/:roomTypeId/merge",
    permissions: ["property.map.manage"],
    riskLevel: "critical"
  },
  { method: "GET", path: "/backoffice/room-types/:roomTypeId/rooms", permissions: ["property.map.read"], riskLevel: "medium" },
  { method: "GET", path: "/backoffice/properties/:propertyId/room-features", permissions: ["property.map.read"], riskLevel: "medium" },
  { method: "POST", path: "/backoffice/properties/:propertyId/room-features", permissions: ["property.map.manage"], riskLevel: "high" },
  { method: "GET", path: "/backoffice/properties/:propertyId/bed-types", permissions: ["property.map.read"], riskLevel: "medium" },
  { method: "POST", path: "/backoffice/properties/:propertyId/bed-types", permissions: ["property.map.manage"], riskLevel: "high" },
  {
    method: "POST",
    path: "/backoffice/properties/:propertyId/imports/property-map/preview",
    permissions: ["property.import"],
    riskLevel: "high"
  },
  {
    method: "POST",
    path: "/backoffice/properties/:propertyId/imports/property-map/commit",
    permissions: ["property.import", "property.map.manage"],
    riskLevel: "critical"
  },
  { method: "GET", path: "/backoffice/properties/:propertyId/imports/:importId", permissions: ["property.import"], riskLevel: "medium" },
  { method: "GET", path: "/backoffice/properties/:propertyId/modules", permissions: ["modules.read"], riskLevel: "medium" },
  { method: "PATCH", path: "/backoffice/properties/:propertyId/modules/:moduleCode", permissions: ["modules.configure"], riskLevel: "high" },
  {
    method: "GET",
    path: "/backoffice/properties/:propertyId/modules/:moduleCode/configuration",
    permissions: ["modules.read"],
    riskLevel: "medium"
  },
  {
    method: "PATCH",
    path: "/backoffice/properties/:propertyId/modules/:moduleCode/configuration",
    permissions: ["modules.configure"],
    riskLevel: "high"
  },
  {
    method: "GET",
    path: "/backoffice/properties/:propertyId/modules/:moduleCode/health",
    permissions: ["modules.read"],
    riskLevel: "medium"
  },
  {
    method: "POST",
    path: "/backoffice/properties/:propertyId/modules/:moduleCode/recalculate-health",
    permissions: ["modules.configure"],
    riskLevel: "high"
  },
  { method: "GET", path: "/backoffice/properties/:propertyId/departments", permissions: ["property.configure"], riskLevel: "medium" },
  { method: "POST", path: "/backoffice/properties/:propertyId/departments", permissions: ["property.configure"], riskLevel: "high" },
  {
    method: "POST",
    path: "/backoffice/properties/:propertyId/departments/:departmentId/users",
    permissions: ["users.invite"],
    riskLevel: "high"
  },
  { method: "GET", path: "/backoffice/properties/:propertyId/housekeeping-settings", permissions: ["property.configure"], riskLevel: "medium" },
  {
    method: "POST",
    path: "/backoffice/properties/:propertyId/housekeeping-sections",
    permissions: ["property.configure"],
    riskLevel: "high"
  },
  {
    method: "POST",
    path: "/backoffice/properties/:propertyId/housekeeping-sections/:sectionId/rooms",
    permissions: ["property.configure"],
    riskLevel: "high"
  },
  {
    method: "PATCH",
    path: "/backoffice/properties/:propertyId/housekeeping-rules/:ruleCode",
    permissions: ["property.configure"],
    riskLevel: "high"
  },
  { method: "GET", path: "/backoffice/properties/:propertyId/maintenance-settings", permissions: ["property.configure"], riskLevel: "medium" },
  {
    method: "POST",
    path: "/backoffice/properties/:propertyId/maintenance-areas",
    permissions: ["property.configure"],
    riskLevel: "high"
  },
  {
    method: "POST",
    path: "/backoffice/properties/:propertyId/maintenance-areas/:areaId/rooms",
    permissions: ["property.configure"],
    riskLevel: "high"
  },
  {
    method: "PATCH",
    path: "/backoffice/properties/:propertyId/maintenance-rules/:ruleCode",
    permissions: ["property.configure"],
    riskLevel: "high"
  },
  { method: "GET", path: "/backoffice/properties/:propertyId/users", permissions: ["users.read"], riskLevel: "medium" },
  { method: "POST", path: "/backoffice/properties/:propertyId/users/invite", permissions: ["users.invite"], riskLevel: "high" },
  { method: "POST", path: "/backoffice/properties/:propertyId/users/:userId/disable", permissions: ["users.disable"], riskLevel: "high" },
  { method: "GET", path: "/backoffice/roles", permissions: ["roles.manage"], riskLevel: "medium" },
  { method: "GET", path: "/backoffice/permissions", permissions: ["permissions.manage"], riskLevel: "medium" },
  { method: "GET", path: "/backoffice/properties/:propertyId/integrations", permissions: ["integrations.read"], riskLevel: "medium" },
  {
    method: "POST",
    path: "/backoffice/properties/:propertyId/integrations/:providerCode/connect",
    permissions: ["integrations.connect", "integrations.manage_credentials"],
    riskLevel: "high"
  },
  {
    method: "GET",
    path: "/backoffice/properties/:propertyId/compliance-settings",
    permissions: ["compliance.configure"],
    riskLevel: "high"
  },
  {
    method: "PATCH",
    path: "/backoffice/properties/:propertyId/compliance-settings",
    permissions: ["compliance.configure"],
    riskLevel: "critical"
  },
  { method: "GET", path: "/backoffice/properties/:propertyId/billing-settings", permissions: ["billing.configure"], riskLevel: "high" },
  { method: "PATCH", path: "/backoffice/properties/:propertyId/billing-settings", permissions: ["billing.configure"], riskLevel: "critical" },
  {
    method: "GET",
    path: "/backoffice/properties/:propertyId/accounting-settings",
    permissions: ["accounting.configure"],
    riskLevel: "high"
  },
  {
    method: "PATCH",
    path: "/backoffice/properties/:propertyId/accounting-settings",
    permissions: ["accounting.configure"],
    riskLevel: "critical"
  },
  { method: "GET", path: "/backoffice/properties/:propertyId/ai-settings", permissions: ["ai.configure"], riskLevel: "high" },
  { method: "PATCH", path: "/backoffice/properties/:propertyId/ai-settings", permissions: ["ai.configure"], riskLevel: "critical" },
  { method: "GET", path: "/backoffice/properties/:propertyId/ai/suggestions", permissions: ["ai.configure"], riskLevel: "high" },
  { method: "POST", path: "/backoffice/properties/:propertyId/ai/suggestions", permissions: ["ai.configure"], riskLevel: "high" },
  {
    method: "POST",
    path: "/backoffice/properties/:propertyId/ai/suggestions/:suggestionId/apply",
    permissions: ["ai.configure"],
    riskLevel: "critical"
  },
  { method: "GET", path: "/backoffice/properties/:propertyId/templates", permissions: ["templates.read"], riskLevel: "medium" },
  { method: "POST", path: "/backoffice/properties/:propertyId/templates", permissions: ["templates.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/backoffice/properties/:propertyId/templates/:templateId", permissions: ["templates.manage"], riskLevel: "high" },
  { method: "POST", path: "/backoffice/properties/:propertyId/qr-codes", permissions: ["property.map.manage"], riskLevel: "high" },
  { method: "GET", path: "/backoffice/properties/:propertyId/qr-codes", permissions: ["property.map.read"], riskLevel: "medium" },
  { method: "POST", path: "/backoffice/properties/:propertyId/qr-codes/bulk", permissions: ["property.map.manage"], riskLevel: "high" },
  { method: "GET", path: "/backoffice/properties/:propertyId/audit", permissions: ["audit.read"], riskLevel: "high" },
  { method: "GET", path: "/modules/catalog", permissions: ["modules.read"], riskLevel: "low" },
  { method: "GET", path: "/modules/:moduleCode/dependencies", permissions: ["modules.read"], riskLevel: "low" },
  { method: "GET", path: "/properties/:propertyId/modules", permissions: ["modules.read"], riskLevel: "low" },
  { method: "PATCH", path: "/properties/:propertyId/modules/:moduleCode/enable", permissions: ["modules.enable"], riskLevel: "high" },
  { method: "PATCH", path: "/properties/:propertyId/modules/:moduleCode/disable", permissions: ["modules.disable"], riskLevel: "high" },
  { method: "GET", path: "/integrations/categories", permissions: ["integrations.read"], riskLevel: "low" },
  { method: "GET", path: "/integrations/providers", permissions: ["integrations.read"], riskLevel: "low" },
  { method: "GET", path: "/properties/:propertyId/integrations", permissions: ["integrations.read"], riskLevel: "low" },
  {
    method: "POST",
    path: "/properties/:propertyId/integrations/:providerCode/connect",
    permissions: ["integrations.connect", "integrations.manage_credentials"],
    riskLevel: "high"
  },
  { method: "PATCH", path: "/properties/:propertyId/integrations/:connectionId", permissions: ["integrations.connect"], riskLevel: "medium" },
  {
    method: "DELETE",
    path: "/properties/:propertyId/integrations/:connectionId",
    permissions: ["integrations.disconnect"],
    riskLevel: "high"
  },
  { method: "POST", path: "/properties/:propertyId/integrations/:connectionId/test", permissions: ["integrations.test"], riskLevel: "medium" },
  { method: "GET", path: "/properties/:propertyId/integrations/:connectionId/events", permissions: ["integrations.read"], riskLevel: "low" },
  { method: "POST", path: "/offline/sync", permissions: ["ai.tool.execute"], riskLevel: "medium" },
  { method: "GET", path: "/properties/:propertyId/offline-sync-records", permissions: ["ai.tool.execute"], riskLevel: "low" },
  { method: "GET", path: "/properties/:propertyId/dashboard", permissions: ["pms.reservation.read"], riskLevel: "low" },
  { method: "GET", path: "/properties/:propertyId/rooms", permissions: ["pms.reservation.read"], riskLevel: "low" },
  { method: "POST", path: "/properties/:propertyId/rooms", permissions: ["pms.reservation.modify"], riskLevel: "medium" },
  { method: "GET", path: "/properties/:propertyId/room-types", permissions: ["pms.reservation.read"], riskLevel: "low" },
  { method: "GET", path: "/properties/:propertyId/reservations", permissions: ["pms.reservation.read"], riskLevel: "low" },
  { method: "POST", path: "/properties/:propertyId/availability/quote", permissions: ["pms.reservation.read"], riskLevel: "low" },
  { method: "POST", path: "/properties/:propertyId/reservations", permissions: ["pms.reservation.create"], riskLevel: "medium" },
  { method: "GET", path: "/reservations/:id", permissions: ["pms.reservation.read"], riskLevel: "low" },
  { method: "PATCH", path: "/reservations/:id", permissions: ["pms.reservation.modify"], riskLevel: "medium" },
  { method: "POST", path: "/reservations/:id/assign-room", permissions: ["pms.reservation.modify"], riskLevel: "high" },
  { method: "POST", path: "/reservations/:id/check-in", permissions: ["pms.checkin.execute"], riskLevel: "high" },
  { method: "POST", path: "/reservations/:id/check-out", permissions: ["pms.checkout.execute"], riskLevel: "high" },
  { method: "POST", path: "/reservations/:id/cancel", permissions: ["pms.reservation.modify"], riskLevel: "high" },
  { method: "POST", path: "/reservations/:id/no-show", permissions: ["pms.reservation.modify"], riskLevel: "high" },
  { method: "GET", path: "/reservations/:id/folio", permissions: ["pms.reservation.read"], riskLevel: "low" },
  { method: "POST", path: "/folios/:id/lines", permissions: ["folio.charge.post"], riskLevel: "medium" },
  { method: "POST", path: "/folios/:id/payments", permissions: ["payment.capture"], riskLevel: "high" },
  { method: "POST", path: "/payments/:id/refund", permissions: ["payment.refund", "ai.high_risk.confirm"], riskLevel: "critical" },
  { method: "POST", path: "/folios/:id/close", permissions: ["folio.charge.post"], riskLevel: "medium" },
  { method: "GET", path: "/properties/:propertyId/invoices", permissions: ["invoice.issue"], riskLevel: "medium" },
  { method: "GET", path: "/properties/:propertyId/invoice-branding", permissions: ["billing.compliance.view"], riskLevel: "low" },
  { method: "PATCH", path: "/properties/:propertyId/invoice-branding", permissions: ["property.configure"], riskLevel: "high" },
  { method: "POST", path: "/invoices/drafts", permissions: ["invoice.issue"], riskLevel: "high" },
  { method: "PATCH", path: "/invoices/:id", permissions: ["invoice.issue"], riskLevel: "high" },
  { method: "POST", path: "/invoices/:id/issue", permissions: ["invoice.issue"], riskLevel: "critical" },
  { method: "POST", path: "/invoices/:id/cancel", permissions: ["invoice.cancel"], riskLevel: "critical" },
  { method: "POST", path: "/invoices/:id/rectify", permissions: ["invoice.issue"], riskLevel: "high" },
  { method: "GET", path: "/invoices/:id/rectifications", permissions: ["analytics.read"], riskLevel: "low" },
  // Folio/Billing advanced (Sprint 40). All medium risk: they mutate folios
  // and invoices but stay idempotent and reversible (split/move can be undone
  // by another move; mark-paid is mirrored by refundPayment).
  { method: "POST", path: "/folios/:id/split", permissions: ["billing.invoice.issue", "folio.charge.post"], riskLevel: "medium" },
  { method: "POST", path: "/folios/:sourceId/move-charges", permissions: ["billing.invoice.issue", "folio.charge.post"], riskLevel: "medium" },
  { method: "POST", path: "/invoices/:id/mark-paid", permissions: ["billing.invoice.issue", "payment.capture"], riskLevel: "medium" },
  { method: "POST", path: "/invoices/:id/send-email", permissions: ["billing.invoice.issue"], riskLevel: "medium" },
  { method: "GET", path: "/reports/properties/:propertyId/catalog", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/reports/properties/:propertyId/reservations", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/reports/properties/:propertyId/billing", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "POST", path: "/reports/properties/:propertyId/export", permissions: ["analytics.export"], riskLevel: "high" },
  { method: "GET", path: "/organizations/:organizationId/accounts", permissions: ["accounting.journal.post"], riskLevel: "medium" },
  { method: "GET", path: "/organizations/:organizationId/journal-entries", permissions: ["accounting.journal.post"], riskLevel: "medium" },
  { method: "POST", path: "/journal-entries/drafts", permissions: ["accounting.journal.post"], riskLevel: "high" },
  { method: "POST", path: "/journal-entries/:id/post", permissions: ["accounting.journal.post", "ai.high_risk.confirm"], riskLevel: "critical" },
  { method: "GET", path: "/properties/:propertyId/supplier-bills", permissions: ["accounting.journal.post"], riskLevel: "medium" },
  { method: "POST", path: "/supplier-bills/drafts", permissions: ["ai.tool.execute"], riskLevel: "medium" },
  { method: "GET", path: "/banking/accounts", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "POST", path: "/banking/accounts", permissions: ["banking.reconcile"], riskLevel: "high" },
  { method: "GET", path: "/banking/accounts/:id/balance", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/banking/accounts/:id/statements", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "POST", path: "/banking/accounts/:id/statements/import-csv", permissions: ["banking.reconcile"], riskLevel: "high" },
  { method: "GET", path: "/banking/accounts/:id/reconciliation-status", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/banking/statements/:id", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "POST", path: "/banking/statements/:id/auto-match", permissions: ["banking.reconcile"], riskLevel: "high" },
  { method: "POST", path: "/banking/lines/:bankLineId/match", permissions: ["banking.reconcile"], riskLevel: "high" },
  { method: "DELETE", path: "/banking/lines/:bankLineId/match", permissions: ["banking.reconcile"], riskLevel: "high" },
  { method: "GET", path: "/properties/:propertyId/housekeeping/board", permissions: ["housekeeping.task.manage"], riskLevel: "low" },
  { method: "POST", path: "/housekeeping/tasks", permissions: ["housekeeping.task.manage"], riskLevel: "low" },
  { method: "PATCH", path: "/housekeeping/tasks/:id", permissions: ["housekeeping.task.manage"], riskLevel: "low" },
  { method: "POST", path: "/housekeeping/tasks/:id/photo", permissions: ["housekeeping.task.manage"], riskLevel: "low" },
  { method: "POST", path: "/rooms/:id/mark-clean", permissions: ["housekeeping.task.manage"], riskLevel: "medium" },
  { method: "POST", path: "/rooms/:id/mark-inspected", permissions: ["housekeeping.task.manage"], riskLevel: "high" },
  { method: "GET", path: "/properties/:propertyId/work-orders", permissions: ["maintenance.workorder.manage"], riskLevel: "low" },
  { method: "POST", path: "/work-orders", permissions: ["maintenance.workorder.manage"], riskLevel: "low" },
  { method: "PATCH", path: "/work-orders/:id", permissions: ["maintenance.workorder.manage"], riskLevel: "low" },
  { method: "POST", path: "/work-orders/:id/media", permissions: ["maintenance.workorder.manage"], riskLevel: "low" },
  {
    method: "POST",
    path: "/work-orders/:id/block-room",
    permissions: ["maintenance.workorder.manage", "ai.high_risk.confirm"],
    riskLevel: "critical"
  },
  { method: "POST", path: "/work-orders/:id/resolve", permissions: ["maintenance.workorder.manage"], riskLevel: "medium" },
  // PILOT-D4 · Salud de las integraciones ES (sin propertyId — vista global)
  { method: "GET", path: "/compliance/health", permissions: ["billing.compliance.view"], riskLevel: "low" },
  { method: "PATCH", path: "/compliance/properties/:propertyId/items/:requirementCode", permissions: ["compliance.configure"], riskLevel: "medium" },
  { method: "PATCH", path: "/compliance/properties/:propertyId/profile", permissions: ["compliance.configure"], riskLevel: "medium" },
  { method: "POST", path: "/compliance/properties/:propertyId/tasks", permissions: ["compliance.configure"], riskLevel: "low" },
  { method: "PATCH", path: "/compliance/tasks/:id", permissions: ["compliance.configure"], riskLevel: "low" },
  { method: "DELETE", path: "/compliance/tasks/:id", permissions: ["compliance.configure"], riskLevel: "low" },
  { method: "POST", path: "/compliance/properties/:propertyId/documents", permissions: ["compliance.configure"], riskLevel: "low" },
  { method: "POST", path: "/compliance/ocr/extract-dates", permissions: ["compliance.configure"], riskLevel: "low" },
  { method: "POST", path: "/properties/:propertyId/cancellation-policies", permissions: ["pms.reservation.modify"], riskLevel: "low" },
  { method: "PATCH", path: "/cancellation-policies/:id", permissions: ["pms.reservation.modify"], riskLevel: "low" },
  { method: "DELETE", path: "/cancellation-policies/:id", permissions: ["pms.reservation.modify"], riskLevel: "low" },
  { method: "POST", path: "/reservations/:id/apply-cancellation-fee", permissions: ["folio.charge.post", "pms.reservation.modify"], riskLevel: "medium" },
  { method: "POST", path: "/reservations/:id/apply-no-show-fee", permissions: ["folio.charge.post", "pms.reservation.modify"], riskLevel: "medium" },
  { method: "POST", path: "/organizations/:organizationId/tour-operators", permissions: ["channel_manager.manage"], riskLevel: "low" },
  { method: "PATCH", path: "/tour-operators/:id", permissions: ["channel_manager.manage"], riskLevel: "low" },
  { method: "POST", path: "/properties/:propertyId/allotments", permissions: ["channel_manager.manage"], riskLevel: "low" },
  { method: "PATCH", path: "/allotments/:id", permissions: ["channel_manager.manage"], riskLevel: "low" },
  { method: "DELETE", path: "/allotments/:id", permissions: ["channel_manager.manage"], riskLevel: "medium" },
  { method: "POST", path: "/properties/:propertyId/allotments/release-expired", permissions: ["channel_manager.manage"], riskLevel: "medium" },
  { method: "POST", path: "/reservations/:id/folios", permissions: ["folio.charge.post"], riskLevel: "low" },
  { method: "POST", path: "/reservations/:id/routing-rules", permissions: ["folio.charge.post"], riskLevel: "low" },
  { method: "PATCH", path: "/routing-rules/:id", permissions: ["folio.charge.post"], riskLevel: "low" },
  { method: "DELETE", path: "/routing-rules/:id", permissions: ["folio.charge.post"], riskLevel: "low" },
  { method: "POST", path: "/folio-lines/:lineId/transfer", permissions: ["folio.charge.post"], riskLevel: "medium" },
  { method: "POST", path: "/properties/:propertyId/stock-locations", permissions: ["inventory.manage"], riskLevel: "low" },
  { method: "POST", path: "/properties/:propertyId/inventory-items", permissions: ["inventory.manage"], riskLevel: "low" },
  { method: "POST", path: "/properties/:propertyId/stock-movements", permissions: ["inventory.manage"], riskLevel: "low" },
  { method: "POST", path: "/properties/:propertyId/menu-items", permissions: ["inventory.manage"], riskLevel: "low" },
  { method: "POST", path: "/menu-items/:id/recipes", permissions: ["inventory.manage"], riskLevel: "low" },
  { method: "DELETE", path: "/menu-recipes/:id", permissions: ["inventory.manage"], riskLevel: "low" },
  { method: "DELETE", path: "/compliance/documents/:id", permissions: ["compliance.configure"], riskLevel: "medium" },
  { method: "POST", path: "/pos/tickets", permissions: ["folio.charge.post"], riskLevel: "low" },
  { method: "POST", path: "/pos/tickets/:id/lines", permissions: ["folio.charge.post"], riskLevel: "low" },
  { method: "POST", path: "/pos/tickets/:id/close", permissions: ["folio.charge.post"], riskLevel: "medium" },
  { method: "GET", path: "/properties/:propertyId/capex", permissions: ["asset.capex.approve"], riskLevel: "medium" },
  { method: "GET", path: "/properties/:propertyId/assets", permissions: ["maintenance.workorder.manage"], riskLevel: "low" },
  { method: "POST", path: "/assets", permissions: ["maintenance.workorder.manage"], riskLevel: "medium" },
  { method: "PATCH", path: "/assets/:id", permissions: ["maintenance.workorder.manage"], riskLevel: "medium" },
  { method: "GET", path: "/properties/:propertyId/fixed-assets", permissions: ["accounting.journal.post"], riskLevel: "medium" },
  { method: "GET", path: "/properties/:propertyId/room-profitability", permissions: ["pms.reservation.read"], riskLevel: "medium" },
  { method: "GET", path: "/properties/:propertyId/owner-dashboard", permissions: ["pms.reservation.read"], riskLevel: "medium" },
  { method: "POST", path: "/capex-projects", permissions: ["asset.capex.approve"], riskLevel: "high" },
  { method: "PATCH", path: "/capex-projects/:id", permissions: ["asset.capex.approve"], riskLevel: "high" },
  { method: "POST", path: "/capex-projects/:id/items", permissions: ["asset.capex.approve"], riskLevel: "high" },
  { method: "GET", path: "/properties/:propertyId/conversations", permissions: ["ai.tool.execute"], riskLevel: "low" },
  { method: "GET", path: "/conversations/:id/messages", permissions: ["ai.tool.execute"], riskLevel: "low" },
  { method: "POST", path: "/conversations/:id/messages", permissions: ["ai.tool.execute"], riskLevel: "medium" },
  { method: "POST", path: "/conversations/:id/ai-draft", permissions: ["ai.tool.execute"], riskLevel: "low" },
  { method: "POST", path: "/service-requests", permissions: ["ai.tool.execute"], riskLevel: "low" },
  { method: "PATCH", path: "/service-requests/:id", permissions: ["ai.tool.execute"], riskLevel: "low" },
  { method: "GET", path: "/properties/:propertyId/compliance/inbox", permissions: ["compliance.ses.submit"], riskLevel: "medium" },
  {
    method: "GET",
    path: "/compliance/spain/properties/:propertyId/guest-register/settings",
    permissions: ["guest_register.configure"],
    riskLevel: "medium"
  },
  {
    method: "PATCH",
    path: "/compliance/spain/properties/:propertyId/guest-register/settings",
    permissions: ["guest_register.configure", "compliance.ses.configure"],
    riskLevel: "high"
  },
  {
    method: "GET",
    path: "/compliance/spain/reservations/:reservationId/guest-register",
    permissions: ["guest_register.read"],
    riskLevel: "medium"
  },
  {
    method: "POST",
    path: "/compliance/spain/reservations/:reservationId/guest-register",
    permissions: ["guest_register.create"],
    riskLevel: "high"
  },
  { method: "PATCH", path: "/compliance/spain/guest-register/:recordId", permissions: ["guest_register.edit"], riskLevel: "high" },
  {
    method: "POST",
    path: "/compliance/spain/guest-register/:recordId/validate",
    permissions: ["guest_register.read"],
    riskLevel: "medium"
  },
  {
    method: "POST",
    path: "/compliance/spain/guest-register/:recordId/sign",
    permissions: ["guest_register.sign", "pms.checkin.execute"],
    riskLevel: "high"
  },
  {
    method: "POST",
    path: "/compliance/spain/guest-register/:recordId/mark-identity-verified",
    permissions: ["guest_register.edit"],
    riskLevel: "high"
  },
  {
    method: "POST",
    path: "/compliance/spain/guest-register/:recordId/queue-submission",
    permissions: ["guest_register.submit", "compliance.ses.submit"],
    riskLevel: "high"
  },
  {
    method: "POST",
    path: "/compliance/spain/guest-register/:recordId/correct",
    permissions: ["guest_register.correct"],
    riskLevel: "high"
  },
  {
    method: "POST",
    path: "/compliance/spain/guest-register/:recordId/annul",
    permissions: ["guest_register.annul"],
    riskLevel: "critical"
  },
  {
    method: "POST",
    path: "/compliance/spain/identity-document/temporary-scan",
    permissions: ["guest_register.create"],
    riskLevel: "high"
  },
  {
    method: "POST",
    path: "/compliance/spain/identity-document/discard-event",
    permissions: ["guest_register.create"],
    riskLevel: "high"
  },
  {
    method: "GET",
    path: "/compliance/authority/properties/:propertyId/inbox",
    permissions: ["guest_register.read"],
    riskLevel: "medium"
  },
  {
    method: "GET",
    path: "/compliance/authority/properties/:propertyId/submissions",
    permissions: ["guest_register.read"],
    riskLevel: "medium"
  },
  {
    method: "GET",
    path: "/compliance/authority/submissions/:submissionId",
    permissions: ["guest_register.read", "guest_register.view_sensitive"],
    riskLevel: "high"
  },
  {
    method: "POST",
    path: "/compliance/authority/submissions/:submissionId/retry",
    permissions: ["guest_register.submit"],
    riskLevel: "high"
  },
  {
    method: "POST",
    path: "/compliance/ses-hospedajes/properties/:propertyId/batches/generate",
    permissions: ["guest_register.export", "compliance.ses.export"],
    riskLevel: "high"
  },
  {
    method: "POST",
    path: "/compliance/ses-hospedajes/properties/:propertyId/batches/:batchId/submit",
    permissions: ["guest_register.submit", "compliance.ses.submit"],
    riskLevel: "critical"
  },
  {
    method: "GET",
    path: "/compliance/ses-hospedajes/properties/:propertyId/batches/:batchId/download",
    permissions: ["guest_register.export", "compliance.ses.export"],
    riskLevel: "high"
  },
  {
    method: "POST",
    path: "/compliance/ses-hospedajes/properties/:propertyId/batches/:batchId/mark-manually-uploaded",
    permissions: ["guest_register.submit", "compliance.ses.submit"],
    riskLevel: "high"
  },
  {
    method: "POST",
    path: "/compliance/ses-hospedajes/properties/:propertyId/test-connection",
    permissions: ["compliance.ses.configure"],
    riskLevel: "medium"
  },
  // AI Booking Agent — natural-language reservation parsing (read-only, no writes).
  { method: "POST", path: "/properties/:propertyId/reservations/ai-parse", permissions: ["pms.reservation.read"], riskLevel: "low" },
  // Guest journey activity feed (chat + housekeeping + maintenance + service requests).
  { method: "GET", path: "/reservations/:id/activity", permissions: ["pms.reservation.read"], riskLevel: "low" },
  // Property Mapper — AI document → property structure (extract is read-only analysis; apply writes rooms).
  { method: "POST", path: "/properties/:propertyId/mapper/extract", permissions: ["property.map.read"], riskLevel: "low" },
  { method: "POST", path: "/properties/:propertyId/mapper/apply", permissions: ["rooms.manage"], riskLevel: "high" },
  // Guest profiles (organization-scoped CRUD).
  { method: "GET", path: "/guests", permissions: ["guests.read"], riskLevel: "medium" },
  { method: "GET", path: "/guests/:id", permissions: ["guests.read"], riskLevel: "medium" },
  { method: "POST", path: "/guests", permissions: ["guests.manage"], riskLevel: "high" },
  { method: "PATCH", path: "/guests/:id", permissions: ["guests.manage"], riskLevel: "high" },
  // GDPR DSAR + Right-to-erasure (Sprint 31). Guarded by compliance.gdpr.manage.
  { method: "POST", path: "/gdpr/requests", permissions: ["compliance.gdpr.manage"], riskLevel: "critical" },
  { method: "GET", path: "/gdpr/requests", permissions: ["compliance.gdpr.manage"], riskLevel: "medium" },
  { method: "GET", path: "/gdpr/requests/:id", permissions: ["compliance.gdpr.manage"], riskLevel: "medium" },
  { method: "POST", path: "/gdpr/requests/:id/acknowledge", permissions: ["compliance.gdpr.manage"], riskLevel: "high" },
  { method: "POST", path: "/gdpr/requests/:id/fulfill-dsar", permissions: ["compliance.gdpr.manage"], riskLevel: "critical" },
  { method: "POST", path: "/gdpr/requests/:id/execute-erasure", permissions: ["compliance.gdpr.manage"], riskLevel: "critical" },
  { method: "POST", path: "/gdpr/requests/:id/reject", permissions: ["compliance.gdpr.manage"], riskLevel: "high" },
  // Sprint 35 — PII backfill job. Guarded by compliance.gdpr.manage (same
  // sensitive perm as the GDPR DSAR endpoints above). Touches every PII row,
  // hence critical risk.
  { method: "POST", path: "/admin/jobs/pii-backfill", permissions: ["compliance.gdpr.manage"], riskLevel: "critical" },
  { method: "GET", path: "/properties/:propertyId/guest-register-records", permissions: ["compliance.ses.submit"], riskLevel: "medium" },
  { method: "POST", path: "/guest-register-records/:id/sign", permissions: ["pms.checkin.execute"], riskLevel: "high" },
  { method: "PATCH", path: "/guest-register-records/:id/correct", permissions: ["compliance.ses.submit"], riskLevel: "high" },
  { method: "POST", path: "/guest-register-records/:id/queue-ses", permissions: ["compliance.ses.submit"], riskLevel: "high" },
  {
    method: "GET",
    path: "/properties/:propertyId/ses-hospedajes/submissions",
    permissions: ["compliance.ses.submit"],
    riskLevel: "medium"
  },
  { method: "PATCH", path: "/ses-hospedajes/submissions/:id/status", permissions: ["compliance.ses.submit"], riskLevel: "high" },
  {
    method: "POST",
    path: "/ai/commands/check-in-from-scan",
    permissions: ["ai.tool.execute", "pms.checkin.execute"],
    riskLevel: "high"
  },
  {
    method: "POST",
    path: "/ai/commands/scan-id-document",
    permissions: ["ai.tool.execute"],
    riskLevel: "medium"
  },
  {
    method: "POST",
    path: "/onboarding/ai/suggest-mapping",
    permissions: ["onboarding.ai_map"],
    riskLevel: "low"
  },
  {
    method: "POST",
    path: "/ai/confirmations/:confirmationId/execute",
    permissions: ["ai.tool.execute", "pms.checkin.execute"],
    riskLevel: "critical"
  },
  { method: "GET", path: "/audit-events", permissions: ["ai.high_risk.confirm"], riskLevel: "high" },
  { method: "GET", path: "/audit-events/facets", permissions: ["ai.high_risk.confirm"], riskLevel: "high" },
  { method: "GET", path: "/audit-events/integrity", permissions: ["ai.high_risk.confirm"], riskLevel: "high" },
  { method: "GET", path: "/events", permissions: ["ai.high_risk.confirm"], riskLevel: "high" },
  { method: "GET", path: "/events/integrity", permissions: ["ai.high_risk.confirm"], riskLevel: "high" },
  { method: "GET", path: "/ai/tool-calls", permissions: ["ai.high_risk.confirm"], riskLevel: "high" },
  { method: "GET", path: "/properties/:propertyId/night-audit/business-date", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/properties/:propertyId/night-audit/runs", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "POST", path: "/properties/:propertyId/night-audit/run", permissions: ["accounting.journal.post"], riskLevel: "high" },
  { method: "POST", path: "/accounting/fiscal-periods", permissions: ["accounting.journal.post"], riskLevel: "high" },
  { method: "POST", path: "/accounting/fiscal-periods/:id/close", permissions: ["accounting.journal.post"], riskLevel: "high" },
  { method: "POST", path: "/accounting/fiscal-periods/:id/reopen", permissions: ["accounting.journal.post", "ai.high_risk.confirm"], riskLevel: "high" },
  // Sprint 25 — Year-end close (Spanish PGC).
  { method: "GET", path: "/accounting/fiscal-years", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "POST", path: "/accounting/fiscal-years", permissions: ["accounting.journal.post"], riskLevel: "high" },
  { method: "GET", path: "/accounting/fiscal-years/:id/status", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "POST", path: "/accounting/fiscal-years/:id/close", permissions: ["accounting.journal.post", "ai.high_risk.confirm"], riskLevel: "critical" },
  { method: "POST", path: "/accounting/fiscal-years/:id/reopen", permissions: ["accounting.journal.post", "ai.high_risk.confirm"], riskLevel: "critical" },
  { method: "POST", path: "/folios/:id/invoice", permissions: ["invoice.issue"], riskLevel: "medium" },
  { method: "POST", path: "/verifactu/submissions/:id/retry", permissions: ["compliance.ses.submit"], riskLevel: "medium" },
  { method: "POST", path: "/tbai/submissions/:id/retry", permissions: ["compliance.ses.submit"], riskLevel: "medium" },
  { method: "POST", path: "/igic/submissions/:id/retry", permissions: ["compliance.ses.submit"], riskLevel: "medium" },
  { method: "POST", path: "/ses/submissions/:id/retry", permissions: ["compliance.ses.submit"], riskLevel: "medium" },
  { method: "GET", path: "/accounting/reports/trial-balance", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "GET", path: "/accounting/reports/balance-sheet", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "GET", path: "/accounting/reports/cash-flow", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "GET", path: "/accounting/reports/pnl", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "GET", path: "/accounting/reports/modelo-111", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "GET", path: "/accounting/reports/modelo-115", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "GET", path: "/accounting/reports/modelo-180", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "GET", path: "/commissions/rules", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "POST", path: "/commissions/rules", permissions: ["accounting.journal.post"], riskLevel: "high" },
  { method: "POST", path: "/commissions/rules/:id/deactivate", permissions: ["accounting.journal.post"], riskLevel: "high" },
  { method: "GET", path: "/commissions/accruals", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "GET", path: "/commissions/summary", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "GET", path: "/dashboards/housekeeping", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/front-desk", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/front-desk-queue", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/room-rack", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/housekeeping-mobile", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/maintenance-mobile", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/shift-manager", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/general-manager", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/general-manager/pace", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/operations-director", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/developer/api-reference", permissions: [], riskLevel: "public" },
  { method: "GET", path: "/developer/keyboard-shortcuts", permissions: [], riskLevel: "public" },
  { method: "POST", path: "/rooms/:id/housekeeping-status", permissions: ["housekeeping.task.manage"], riskLevel: "low" },
  { method: "POST", path: "/rooms/:id/sellable", permissions: ["housekeeping.task.manage"], riskLevel: "low" },
  { method: "GET", path: "/copilot/presets", permissions: [], riskLevel: "low" },
  { method: "POST", path: "/copilot/ask", permissions: [], riskLevel: "low" },
  { method: "GET", path: "/guests/:id/timeline", permissions: ["guests.read"], riskLevel: "low" },
  { method: "GET", path: "/properties/:propertyId/night-audit/preflight", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/maintenance", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/finance-position", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "GET", path: "/dashboards/concierge", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/reputation", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/sales-pipeline", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "GET", path: "/dashboards/workforce", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/crm", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/loyalty", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/upsells", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/surveys", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/quality", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/safety", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/inventory", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/procurement", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/groups-events", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/pos", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/channel-performance", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/energy", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/sustainability", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/assets", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/room-profitability", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/analytics-center", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "GET", path: "/dashboards/portfolio", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "GET", path: "/dashboards/property-overview", permissions: ["analytics.read"], riskLevel: "low" },
  // Payroll bridge to gestoría (Sprint 23 — Track 5)
  { method: "GET", path: "/payroll/contracts", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "POST", path: "/payroll/contracts", permissions: ["payroll.manage"], riskLevel: "high" },
  { method: "POST", path: "/payroll/contracts/:id/deactivate", permissions: ["payroll.manage"], riskLevel: "high" },
  { method: "GET", path: "/payroll/periods", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "POST", path: "/payroll/periods", permissions: ["payroll.manage"], riskLevel: "high" },
  { method: "POST", path: "/payroll/periods/:id/calculate", permissions: ["payroll.manage"], riskLevel: "high" },
  { method: "GET", path: "/payroll/periods/:id/slips", permissions: ["analytics.read"], riskLevel: "medium" },
  { method: "GET", path: "/payroll/periods/:id/export", permissions: ["analytics.read"], riskLevel: "medium" },
  // Multi-currency exchange rates (Sprint 24)
  { method: "GET", path: "/finance/exchange-rates", permissions: ["analytics.read"], riskLevel: "low" },
  { method: "POST", path: "/finance/exchange-rates", permissions: ["accounting.journal.post"], riskLevel: "high" },
  // Notification engine (Sprint 26)
  { method: "GET", path: "/notifications/templates", permissions: [], riskLevel: "low" },
  { method: "POST", path: "/notifications/templates", permissions: ["notifications.manage"], riskLevel: "medium" },
  { method: "POST", path: "/notifications/templates/:id/deactivate", permissions: ["notifications.manage"], riskLevel: "medium" },
  { method: "GET", path: "/notifications/deliveries", permissions: [], riskLevel: "low" },
  { method: "POST", path: "/notifications/deliveries/:id/retry", permissions: ["notifications.manage"], riskLevel: "medium" },
  { method: "POST", path: "/notifications/dispatch", permissions: ["notifications.manage"], riskLevel: "high" },
  { method: "GET", path: "/notifications/template-stats", permissions: [], riskLevel: "low" },
  // Sprint 50 — AI Human Review Queue (HITL). Reads gated by AI governance read;
  // decisions require the high-risk confirmation permission.
  { method: "GET", path: "/ai-operations/review/queue", permissions: ["ai_governance.read"], riskLevel: "medium" },
  { method: "GET", path: "/ai-operations/review/stats", permissions: ["ai_governance.read"], riskLevel: "medium" },
  { method: "GET", path: "/ai-operations/review/:id", permissions: ["ai_governance.read"], riskLevel: "medium" },
  { method: "POST", path: "/ai-operations/review/:id/assign", permissions: ["ai_governance.read"], riskLevel: "medium" },
  { method: "POST", path: "/ai-operations/review/:id/approve", permissions: ["ai.high_risk.confirm"], riskLevel: "high" },
  { method: "POST", path: "/ai-operations/review/:id/reject", permissions: ["ai.high_risk.confirm"], riskLevel: "high" },
  { method: "POST", path: "/ai-operations/review/:id/escalate", permissions: ["ai.high_risk.confirm"], riskLevel: "high" },
  { method: "POST", path: "/ai-operations/review/enqueue", permissions: ["ai.high_risk.confirm"], riskLevel: "high" },
  // Stored card tokens — high-risk because the tokenRef can be replayed against
  // the PSP to charge the cardholder. Restricted to staff who can post folio charges.
  { method: "POST", path: "/payment-tokens", permissions: ["folio.charge.post"], riskLevel: "high" },

  // ------------------------------------------------------------------------
  // Sensitive read-only endpoints — manifest gap fill.
  //
  // assertRoutePermission() returns early for GETs that have no manifest entry,
  // which leaves read access to financial submissions, PII profiles, allotment
  // inventory and guest-portal session data effectively ungated by RBAC. The
  // entries below register the minimum permission expected for each module.
  // ------------------------------------------------------------------------

  // Financial / fiscal submissions — submission detail rows contain customer
  // tax data and authority correlation IDs. Read access piggybacks on the
  // existing compliance.ses.submit perm (same scope as the POST/retry routes).
  { method: "GET", path: "/properties/:propertyId/verifactu/submissions", permissions: ["compliance.ses.submit"], riskLevel: "medium" },
  { method: "GET", path: "/properties/:propertyId/igic/submissions", permissions: ["compliance.ses.submit"], riskLevel: "medium" },
  { method: "GET", path: "/verifactu/submissions/:id", permissions: ["compliance.ses.submit"], riskLevel: "medium" },
  { method: "GET", path: "/tbai/submissions/:id", permissions: ["compliance.ses.submit"], riskLevel: "medium" },
  { method: "GET", path: "/igic/submissions/:id", permissions: ["compliance.ses.submit"], riskLevel: "medium" },
  { method: "GET", path: "/ses/submissions/:id", permissions: ["compliance.ses.submit"], riskLevel: "medium" },

  // Folio + invoice reads — financial PII.
  { method: "GET", path: "/folios/:id/balance", permissions: ["folio.charge.post"], riskLevel: "low" },
  { method: "GET", path: "/invoices/:id", permissions: ["invoice.issue"], riskLevel: "medium" },
  { method: "GET", path: "/invoices/:id/verifactu", permissions: ["compliance.ses.submit"], riskLevel: "medium" },

  // Reservation child reads — folios, routing rules and cancellation charge
  // expose monetary state belonging to the reservation.
  { method: "GET", path: "/reservations/:id/folios", permissions: ["folio.charge.post"], riskLevel: "low" },
  { method: "GET", path: "/reservations/:id/routing-rules", permissions: ["folio.charge.post"], riskLevel: "low" },
  { method: "GET", path: "/reservations/:id/cancellation-charge", permissions: ["pms.reservation.read"], riskLevel: "low" },

  // Allotments / tour-operators — block inventory readable only by channel mgr.
  { method: "GET", path: "/properties/:propertyId/allotments", permissions: ["channel_manager.read"], riskLevel: "low" },
  { method: "GET", path: "/properties/:propertyId/allotments/remaining-for-day", permissions: ["channel_manager.read"], riskLevel: "low" },
  { method: "GET", path: "/properties/:propertyId/allotments/pickup-summary", permissions: ["channel_manager.read"], riskLevel: "low" },
  { method: "GET", path: "/allotments/:id", permissions: ["channel_manager.read"], riskLevel: "low" },
  { method: "GET", path: "/allotments/:id/remaining", permissions: ["channel_manager.read"], riskLevel: "low" },
  { method: "GET", path: "/organizations/:organizationId/tour-operators", permissions: ["channel_manager.read"], riskLevel: "low" },
  { method: "GET", path: "/tour-operators/:id", permissions: ["channel_manager.read"], riskLevel: "low" },

  // Cancellation policies — read-only catalog tied to pms.reservation perms.
  { method: "GET", path: "/properties/:propertyId/cancellation-policies", permissions: ["pms.reservation.read"], riskLevel: "low" },
  { method: "GET", path: "/cancellation-policies/:id", permissions: ["pms.reservation.read"], riskLevel: "low" },

  // CRM reads — guest profiles + segments are PII.
  { method: "GET", path: "/crm/profiles", permissions: ["crm.read"], riskLevel: "medium" },
  { method: "GET", path: "/crm/profiles/:id", permissions: ["crm.read"], riskLevel: "medium" },
  { method: "GET", path: "/crm/duplicates", permissions: ["crm.read"], riskLevel: "medium" },
  { method: "GET", path: "/crm/segments", permissions: ["crm.read"], riskLevel: "medium" },
  { method: "GET", path: "/crm/campaigns", permissions: ["crm.read"], riskLevel: "medium" },
  { method: "GET", path: "/crm/loyalty", permissions: ["crm.read"], riskLevel: "medium" },

  // Sales / Groups — pipeline reads.
  { method: "GET", path: "/sales/accounts", permissions: ["sales.pipeline.read"], riskLevel: "medium" },
  { method: "GET", path: "/sales/opportunities", permissions: ["sales.pipeline.read"], riskLevel: "medium" },
  { method: "GET", path: "/groups/:id", permissions: ["groups.read"], riskLevel: "medium" },
  { method: "GET", path: "/properties/:propertyId/groups/pickup-summary", permissions: ["groups.read"], riskLevel: "low" },

  // Guest portal sessions — token-scoped reads (the guest token is the auth;
  // the staff permission preHandler must still find a manifest entry).
  { method: "GET", path: "/guest-portal/session/:token", permissions: [], riskLevel: "public" },
  { method: "GET", path: "/guest-portal/session/:token/folio", permissions: [], riskLevel: "public" },
  { method: "GET", path: "/guest-portal/session/:token/upsells", permissions: [], riskLevel: "public" },

  // Auto-generated OpenAPI spec — public so external tooling can fetch the schema.
  { method: "GET", path: "/developer/openapi.yaml", permissions: [], riskLevel: "public" },

  // audit 2026-06 R2 · #5: PII / finance / compliance GET routes added to manifest
  // so RBAC_STRICT=true can enforce them without logging them as unmapped.
  // Permissions use existing PermissionKey values (no new perms added here).
  { method: "GET", path: "/guests", permissions: ["pms.checkin.execute"], riskLevel: "high" },
  { method: "GET", path: "/guests/:id", permissions: ["pms.checkin.execute"], riskLevel: "high" },
  { method: "GET", path: "/guests/:id/timeline", permissions: ["pms.checkin.execute"], riskLevel: "high" },
  { method: "GET", path: "/folios/:id/balance", permissions: ["invoice.issue"], riskLevel: "high" },
  { method: "GET", path: "/invoices/:id", permissions: ["invoice.issue"], riskLevel: "critical" },
  { method: "GET", path: "/invoices/:id/rectifications", permissions: ["invoice.cancel"], riskLevel: "critical" },
  { method: "GET", path: "/invoices/:id/verifactu", permissions: ["invoice.issue"], riskLevel: "critical" },
  { method: "GET", path: "/compliance/health", permissions: ["compliance.configure"], riskLevel: "low" },
  { method: "GET", path: "/compliance/properties/:propertyId/center", permissions: ["compliance.configure"], riskLevel: "medium" },
  { method: "GET", path: "/compliance/properties/:propertyId/tasks", permissions: ["compliance.configure"], riskLevel: "medium" },
  { method: "GET", path: "/compliance/properties/:propertyId/documents", permissions: ["compliance.configure"], riskLevel: "medium" },
  { method: "GET", path: "/compliance/properties/:propertyId/alerts", permissions: ["compliance.configure"], riskLevel: "medium" },
  { method: "GET", path: "/compliance/properties/:propertyId/inspection-folder", permissions: ["compliance.configure"], riskLevel: "medium" },
  { method: "GET", path: "/compliance/properties/:propertyId/assistant", permissions: ["compliance.configure"], riskLevel: "medium" },
  { method: "GET", path: "/compliance/spain/properties/:propertyId/guest-register/settings", permissions: ["compliance.ses.configure"], riskLevel: "high" },
  { method: "GET", path: "/compliance/spain/reservations/:reservationId/guest-register", permissions: ["compliance.ses.submit"], riskLevel: "high" },
  { method: "GET", path: "/compliance/authority/properties/:propertyId/inbox", permissions: ["compliance.ses.submit"], riskLevel: "high" },
  { method: "GET", path: "/compliance/authority/properties/:propertyId/submissions", permissions: ["compliance.ses.submit"], riskLevel: "high" },
  { method: "GET", path: "/compliance/authority/submissions/:submissionId", permissions: ["compliance.ses.submit"], riskLevel: "high" },
  { method: "GET", path: "/compliance/ses-hospedajes/properties/:propertyId/batches/:batchId/download", permissions: ["compliance.ses.export"], riskLevel: "critical" },

  // Fase 0: Rate Plan CRUD. Mutations are FAIL-CLOSED without a manifest entry
  // (they throw 500), so these are required for the endpoints to work at all.
  { method: "GET", path: "/properties/:propertyId/rate-plans", permissions: ["revenue.read"], riskLevel: "low" },
  { method: "POST", path: "/properties/:propertyId/rate-plans", permissions: ["revenue.manage_rates"], riskLevel: "medium" },
  { method: "PATCH", path: "/rate-plans/:id", permissions: ["revenue.manage_rates"], riskLevel: "medium" },
  { method: "DELETE", path: "/rate-plans/:id", permissions: ["revenue.manage_rates"], riskLevel: "medium" }
];

export function findRoutePermission(method: string, path: string): ApiRoutePermission | undefined {
  return routePermissionManifest.find((route) => route.method === method.toUpperCase() && route.path === path);
}

export function assertRoutePermission(input: { method: string; path: string; userPermissions: PermissionKey[] }): void {
  const route = findRoutePermission(input.method, input.path);
  if (!route) {
    if (input.method.toUpperCase() === "GET") {
      // Historically any unmapped GET was treated as public (fail-open). That is
      // kept as the DEFAULT so read routes not yet in the manifest don't break,
      // but: (a) we log every gap so it can be mapped, and (b) we fail CLOSED
      // when RBAC_STRICT=true — flip that on once the manifest covers all GETs.
      if (!loggedUnmappedGets.has(input.path)) {
        loggedUnmappedGets.add(input.path);
        console.warn(
          `[rbac] unmapped GET ${input.path} — add it to routePermissionManifest ` +
            `(fail-open by default; set RBAC_STRICT=true to enforce 403)`
        );
      }
      if (process.env.RBAC_STRICT === "true") {
        throw new ForbiddenError(`No route permission manifest entry for GET ${input.path}`);
      }
      return;
    }
    throw new Error(`No route permission manifest entry for ${input.method.toUpperCase()} ${input.path}`);
  }

  assertPermissions(input.userPermissions, route.permissions);
}
