// Local, in-process provider simulator (rate grid v2 · lote api-channel-outbox).
//
// Used by every adapter in `stub` and `sandbox` mode and by the loopback route
// `POST /channel-manager/_sandbox/:provider`. It is NOT an HTTP mock that echoes
// "ok": it performs a STRUCTURAL validation (regex element/attribute scanner,
// no XSD) of the provider payload plus the documented business rules, so a
// sandbox push catches a malformed XML/JSON before any credential exists. It
// is not a certification: only the provider's staging/certification run is.
// The rules below mirror what our builders emit and what the providers
// document (CurrencyCode on BaseByGuestAmt and never on <Rate>, one
// RestrictionStatus per AvailStatusMessage, no advance-booking keys on
// Channex), so a drift between builder and simulator surfaces as a rejection:
//
//   booking  · OTA 2003B v1.1 — OTA_HotelRateAmountNotifRQ / OTA_HotelAvailNotifRQ
//              (RateAmountMessages/RateAmountMessage/StatusApplicationControl
//              [@Start,@End,@InvTypeCode,@RatePlanCode]/Rates/Rate/BaseByGuestAmts/
//              BaseByGuestAmt[@NumberOfGuests,@AmountAfterTax,@DecimalPlaces,@CurrencyCode];
//              AvailStatusMessages/AvailStatusMessage/StatusApplicationControl +
//              LengthsOfStay/LengthOfStay[@MinMaxMessageType,@Time] + RestrictionStatus
//              [@Status,@Restriction,@MinAdvancedBookingOffset,@MaxAdvancedBookingOffset]
//              — AT MOST ONE RestrictionStatus per AvailStatusMessage (OTA 0..1).
//              Answers OTA_*RS with <Success/> or <Errors><Error Code ShortText RecordID/>.
//              Rules: amounts 5..50000, ONE hotel per request, dates within 5 years,
//              Start <= End, offsets like "1D"/"12H"/"1D12H".
//   channex  · JSON POST /api/v1/restrictions {values:[{property_id, rate_plan_id,
//              date | date_from/date_to, days, rate, rates:[{occupancy, rate}],
//              min_stay_arrival, min_stay_through, min_stay, max_stay, closed_to_arrival,
//              closed_to_departure, stop_sell}]} and POST /api/v1/availability
//              {values:[{property_id, room_type_id, date…, availability}]}. Like the
//              real API: a value with wrong data is REJECTED FROM THE UPDATE and comes
//              back as a 200 `meta.warnings[]` entry echoing the value plus
//              `warning: {field: [msg]}`; the other values are applied. Structural
//              problems (no `values` array, malformed JSON) → 400 bad_request with
//              `details: string[]`. Unknown value keys are ignored with a notice.
//   expedia  · EQC AR XML (ns http://www.expediaconnect.com/EQC/AR/2007/02):
//              AvailRateUpdateRQ/Authentication[@username,@password] + Hotel[@id] +
//              AvailRateUpdate/DateRange/RoomType[@id]/RatePlan[@id]/Rate[@currency]/
//              PerDay|PerOccupancy. Answers <Success/>, <Success><Warning code/></Success>
//              (applied with notices, e.g. a rate below 5) or <Error code>. EQC is
//              all-or-nothing: one invalid element fails the whole request.
//
// Failure injection (credentials.simulator on the channel):
//   { failEvery: N }   every N-th request of the channel answers HTTP 429;
//   { latencyMs: ms }  artificial latency; >= the adapter timeout → timed out.
//
// No XML library: the payloads are flat and generated by our own builders, so a
// small attribute/element scanner is enough and keeps the API free of new deps.

import type { AdapterRejection, SimulatorOptions } from "../adapter.types.js";

export type SimulatorProvider = "booking" | "channex" | "expedia";

export type SimulatorRequest = {
  provider: SimulatorProvider;
  /** booking: OTA_HotelRateAmountNotif | OTA_HotelAvailNotif · channex: restrictions | availability | … · expedia: ar | br */
  endpoint: string;
  body: string;
  channelId?: string;
  options?: SimulatorOptions;
  timeoutMs?: number;
};

export type SimulatorResponse = {
  status: number;
  body: string;
  contentType: string;
  timedOut: boolean;
  /** Items the provider accepted (per-item semantics where the provider has them). */
  accepted: number;
  rejected: AdapterRejection[];
  /** Request-level error messages (schema, auth, single-hotel rule…). */
  errors: string[];
  warnings: string[];
};

export const BOOKING_MIN_AMOUNT = 5;
export const BOOKING_MAX_AMOUNT = 50_000;
export const MAX_YEARS_AHEAD = 5;
export const OTA_NS = "http://www.opentravel.org/OTA/2003/05";
export const EQC_AR_NS = "http://www.expediaconnect.com/EQC/AR/2007/02";

// ---------------------------------------------------------------- tiny XML scan

export function xmlAttr(tag: string, name: string): string | null {
  const m = new RegExp(`\\b${name}\\s*=\\s*"([^"]*)"`).exec(tag);
  return m ? decodeXml(m[1] ?? "") : null;
}

/** Every occurrence of `<name …>` (opening or self-closing tag) with its inner text when it has one. */
export function xmlElements(xml: string, name: string): Array<{ tag: string; inner: string }> {
  const out: Array<{ tag: string; inner: string }> = [];
  const re = new RegExp(`<${name}(\\s[^>]*)?(/?)>`, "g");
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml)) !== null) {
    const tag = m[0];
    if (m[2] === "/") {
      out.push({ tag, inner: "" });
      continue;
    }
    const closeIdx = xml.indexOf(`</${name}>`, re.lastIndex);
    const inner = closeIdx === -1 ? "" : xml.slice(re.lastIndex, closeIdx);
    out.push({ tag, inner });
  }
  return out;
}

function decodeXml(value: string): string {
  return value
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

function isValidIsoDate(value: string | null): value is string {
  if (!value || !ISO_DATE.test(value)) return false;
  const d = new Date(`${value}T00:00:00Z`);
  return !Number.isNaN(d.getTime()) && d.toISOString().slice(0, 10) === value;
}

function tooFarAhead(value: string, now: Date): boolean {
  const limit = new Date(Date.UTC(now.getUTCFullYear() + MAX_YEARS_AHEAD, now.getUTCMonth(), now.getUTCDate()));
  return new Date(`${value}T00:00:00Z`).getTime() > limit.getTime();
}

// ---------------------------------------------------------------- Booking OTA

type OtaError = { code: string; shortText: string; recordId?: number };

function otaRs(root: string, errors: OtaError[], warnings: string[]): string {
  const stamp = new Date().toISOString();
  const head = `<?xml version="1.0" encoding="UTF-8"?>\n<${root} xmlns="${OTA_NS}" Version="1.1" TimeStamp="${stamp}">`;
  if (errors.length === 0) {
    const warn = warnings.length
      ? `<Warnings>${warnings.map((w) => `<Warning Type="3" ShortText="${escapeXml(w)}"/>`).join("")}</Warnings>`
      : "";
    return `${head}<Success/>${warn}</${root}>`;
  }
  const body = errors
    .map(
      (e) =>
        `<Error Type="3" Code="${escapeXml(e.code)}"${e.recordId !== undefined ? ` RecordID="${e.recordId}"` : ""} ShortText="${escapeXml(e.shortText)}"/>`
    )
    .join("");
  return `${head}<Errors>${body}</Errors></${root}>`;
}

function validateStatusApplicationControl(
  inner: string,
  index: number,
  requireRatePlan: boolean,
  now: Date,
  errors: OtaError[]
): void {
  const sac = xmlElements(inner, "StatusApplicationControl")[0];
  if (!sac) {
    errors.push({ code: "321", shortText: "StatusApplicationControl is required", recordId: index });
    return;
  }
  const start = xmlAttr(sac.tag, "Start");
  const end = xmlAttr(sac.tag, "End");
  const inv = xmlAttr(sac.tag, "InvTypeCode");
  const plan = xmlAttr(sac.tag, "RatePlanCode");
  if (!isValidIsoDate(start) || !isValidIsoDate(end)) {
    errors.push({ code: "400", shortText: "Start/End must be valid ISO dates", recordId: index });
  } else {
    if (start > end) errors.push({ code: "400", shortText: "Start must not be after End", recordId: index });
    if (tooFarAhead(end, now)) errors.push({ code: "400", shortText: `Dates beyond ${MAX_YEARS_AHEAD} years are not accepted`, recordId: index });
  }
  if (!inv) errors.push({ code: "321", shortText: "InvTypeCode is required", recordId: index });
  if (requireRatePlan && !plan) errors.push({ code: "321", shortText: "RatePlanCode is required", recordId: index });
}

export function simulateBookingOta(xml: string, now: Date = new Date()): Omit<SimulatorResponse, "timedOut" | "contentType"> {
  const errors: OtaError[] = [];
  const warnings: string[] = [];
  const isRate = /<OTA_HotelRateAmountNotifRQ\b/.test(xml);
  const isAvail = /<OTA_HotelAvailNotifRQ\b/.test(xml);
  const root = isRate ? "OTA_HotelRateAmountNotifRS" : "OTA_HotelAvailNotifRS";
  if (!isRate && !isAvail) {
    const body = otaRs("OTA_ErrorRS", [{ code: "450", shortText: "Unknown request root: expected OTA_HotelRateAmountNotifRQ or OTA_HotelAvailNotifRQ" }], []);
    return { status: 200, body, accepted: 0, rejected: [], errors: ["Unknown OTA request root"], warnings };
  }
  if (!xml.includes(OTA_NS)) {
    warnings.push(`Missing OTA namespace ${OTA_NS}`);
  }
  const containerName = isRate ? "RateAmountMessages" : "AvailStatusMessages";
  const messageName = isRate ? "RateAmountMessage" : "AvailStatusMessage";
  const containers = xmlElements(xml, containerName);
  if (containers.length === 0) {
    errors.push({ code: "321", shortText: `${containerName} is required` });
  }
  const hotelCodes = new Set(containers.map((c) => xmlAttr(c.tag, "HotelCode") ?? ""));
  if (containers.length > 0 && (hotelCodes.size !== 1 || hotelCodes.has(""))) {
    errors.push({ code: "450", shortText: "Exactly one HotelCode per request is allowed" });
  }
  const messages = xmlElements(xml, messageName);
  if (containers.length > 0 && messages.length === 0) {
    errors.push({ code: "321", shortText: `At least one ${messageName} is required` });
  }
  if (errors.length > 0) {
    return { status: 200, body: otaRs(root, errors, warnings), accepted: 0, rejected: [], errors: errors.map((e) => e.shortText), warnings };
  }

  messages.forEach((msg, index) => {
    validateStatusApplicationControl(msg.inner, index, isRate, now, errors);
    if (isRate) {
      // ota-rateamountnotif documents CurrencyCode / DecimalPlaces on
      // BaseByGuestAmt; a <Rate CurrencyCode> is an attribute Booking does not
      // read, so a builder emitting it there would send prices without currency.
      for (const rate of xmlElements(msg.inner, "Rate")) {
        if (xmlAttr(rate.tag, "CurrencyCode") !== null) {
          errors.push({ code: "402", shortText: "CurrencyCode belongs on BaseByGuestAmt, not on Rate", recordId: index });
        }
      }
      const amounts = xmlElements(msg.inner, "BaseByGuestAmt");
      if (amounts.length === 0) {
        errors.push({ code: "321", shortText: "BaseByGuestAmt is required", recordId: index });
      }
      for (const a of amounts) {
        const raw = xmlAttr(a.tag, "AmountAfterTax") ?? xmlAttr(a.tag, "AmountBeforeTax");
        const guests = xmlAttr(a.tag, "NumberOfGuests");
        const currency = xmlAttr(a.tag, "CurrencyCode");
        const decimals = xmlAttr(a.tag, "DecimalPlaces");
        const amount = raw === null ? Number.NaN : Number(raw);
        if (!Number.isFinite(amount)) {
          errors.push({ code: "402", shortText: "AmountAfterTax must be numeric", recordId: index });
        } else if (amount < BOOKING_MIN_AMOUNT || amount > BOOKING_MAX_AMOUNT) {
          errors.push({ code: "402", shortText: `AmountAfterTax must be between ${BOOKING_MIN_AMOUNT} and ${BOOKING_MAX_AMOUNT}`, recordId: index });
        }
        if (guests !== null && !(Number(guests) >= 1)) {
          errors.push({ code: "402", shortText: "NumberOfGuests must be >= 1", recordId: index });
        }
        if (currency !== null && !/^[A-Z]{3}$/.test(currency)) {
          errors.push({ code: "402", shortText: "CurrencyCode must be an ISO-4217 code", recordId: index });
        }
        if (decimals !== null && !(Number.isInteger(Number(decimals)) && Number(decimals) >= 0)) {
          errors.push({ code: "402", shortText: "DecimalPlaces must be a non-negative integer", recordId: index });
        }
      }
    } else {
      const limit = xmlAttr(msg.tag, "BookingLimit");
      if (limit !== null && !(Number.isInteger(Number(limit)) && Number(limit) >= 0)) {
        errors.push({ code: "402", shortText: "BookingLimit must be a non-negative integer", recordId: index });
      }
      for (const los of xmlElements(msg.inner, "LengthOfStay")) {
        const type = xmlAttr(los.tag, "MinMaxMessageType");
        const time = xmlAttr(los.tag, "Time");
        if (!type || !["SetMinLOS", "SetMaxLOS", "SetForwardMinStay", "SetForwardMaxStay", "RemoveMinLOS", "RemoveMaxLOS"].includes(type)) {
          errors.push({ code: "402", shortText: `Unknown MinMaxMessageType ${type ?? "(missing)"}`, recordId: index });
        }
        if (time !== null && !(Number.isInteger(Number(time)) && Number(time) >= 0)) {
          errors.push({ code: "402", shortText: "LengthOfStay Time must be a non-negative integer", recordId: index });
        }
      }
      const statuses = xmlElements(msg.inner, "RestrictionStatus");
      // OTA_2003B AvailStatusMessageType: RestrictionStatus minOccurs=0, maxOccurs=1.
      if (statuses.length > 1) {
        errors.push({ code: "402", shortText: "Only one RestrictionStatus per AvailStatusMessage is allowed", recordId: index });
      }
      for (const rs of statuses) {
        const status = xmlAttr(rs.tag, "Status");
        const restriction = xmlAttr(rs.tag, "Restriction");
        if (status !== "Open" && status !== "Close") {
          errors.push({ code: "402", shortText: "RestrictionStatus Status must be Open or Close", recordId: index });
        }
        if (restriction !== null && !["Arrival", "Departure", "Master"].includes(restriction)) {
          errors.push({ code: "402", shortText: "RestrictionStatus Restriction must be Arrival, Departure or Master", recordId: index });
        }
        for (const key of ["MinAdvancedBookingOffset", "MaxAdvancedBookingOffset"]) {
          const offset = xmlAttr(rs.tag, key);
          if (offset !== null && !/^(\d+D|\d+H|\d+D\d+H)$/.test(offset)) {
            errors.push({ code: "402", shortText: `${key} must look like 1D, 12H or 1D12H`, recordId: index });
          }
        }
      }
    }
  });

  const rejectedIdx = new Map<number, OtaError>();
  for (const e of errors) {
    if (e.recordId !== undefined && !rejectedIdx.has(e.recordId)) rejectedIdx.set(e.recordId, e);
  }
  const rejected: AdapterRejection[] = [...rejectedIdx.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([itemIndex, e]) => ({ itemIndex, code: e.code, message: e.shortText }));
  return {
    status: 200,
    body: otaRs(root, errors, warnings),
    accepted: messages.length - rejected.length,
    rejected,
    errors: [],
    warnings
  };
}

// ---------------------------------------------------------------- Channex JSON

type ChannexIssue = { index: number; field: string; message: string };

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === "object" && v !== null && !Array.isArray(v);
}

export function simulateChannex(endpoint: string, rawBody: string): Omit<SimulatorResponse, "timedOut" | "contentType"> {
  const path = endpoint.replace(/^\/?api\/v1\//, "").replace(/^\//, "");
  let parsed: unknown;
  try {
    parsed = rawBody.length ? JSON.parse(rawBody) : {};
  } catch {
    return {
      status: 400,
      body: JSON.stringify({ errors: { code: "bad_request", title: "Malformed JSON" } }),
      accepted: 0,
      rejected: [],
      errors: ["Malformed JSON"],
      warnings: []
    };
  }
  if (path === "channels") {
    const body = { data: [{ id: "sbx-channel-booking", type: "channel", attributes: { channel: "BookingCom", title: "Booking.com (simulado)", is_active: true } }, { id: "sbx-channel-expedia", type: "channel", attributes: { channel: "Expedia", title: "Expedia (simulado)", is_active: true } }] };
    return { status: 200, body: JSON.stringify(body), accepted: 0, rejected: [], errors: [], warnings: [] };
  }
  if (path.startsWith("booking_revisions/feed")) {
    return { status: 200, body: JSON.stringify({ data: [], meta: { next_cursor: null } }), accepted: 0, rejected: [], errors: [], warnings: [] };
  }
  if (/^booking_revisions\/[^/]+\/ack$/.test(path)) {
    return { status: 200, body: JSON.stringify({ meta: { message: "Success" } }), accepted: 1, rejected: [], errors: [], warnings: [] };
  }
  if (path !== "restrictions" && path !== "availability") {
    return {
      status: 404,
      body: JSON.stringify({ errors: { code: "not_found", title: `Unknown endpoint /api/v1/${path}` } }),
      accepted: 0,
      rejected: [],
      errors: [`Unknown endpoint /api/v1/${path}`],
      warnings: []
    };
  }
  const values = isRecord(parsed) && Array.isArray(parsed.values) ? (parsed.values as unknown[]) : null;
  if (!values) {
    return {
      status: 400,
      body: JSON.stringify({ errors: { code: "bad_request", title: "Bad Request", details: ["values is required"] } }),
      accepted: 0,
      rejected: [],
      errors: ["values is required"],
      warnings: []
    };
  }
  const issues: ChannexIssue[] = [];
  const warnings: string[] = [];
  const knownKeys =
    path === "restrictions"
      ? new Set(["property_id", "rate_plan_id", "date", "date_from", "date_to", "days", "rate", "rates", "min_stay_arrival", "min_stay_through", "min_stay", "max_stay", "closed_to_arrival", "closed_to_departure", "stop_sell"])
      : new Set(["property_id", "room_type_id", "date", "date_from", "date_to", "days", "availability"]);
  values.forEach((v, index) => {
    if (isRecord(v)) {
      const unknown = Object.keys(v).filter((k) => !knownKeys.has(k));
      // min/max_advance_days are not in the Channex restrictions vocabulary:
      // named explicitly so a builder regression reads as what it is.
      const advance: string[] = unknown.filter((k) => k === "min_advance_days" || k === "max_advance_days");
      if (advance.length > 0) warnings.push(`values[${index}]: ${advance.join(", ")} outside the Channex restrictions vocabulary (ignored; Channex has no advance-booking restriction)`);
      const rest = unknown.filter((k) => !advance.includes(k));
      if (rest.length > 0) warnings.push(`values[${index}]: unknown keys ignored (${rest.join(", ")})`);
    }
    if (!isRecord(v)) {
      issues.push({ index, field: "value", message: "must be an object" });
      return;
    }
    if (typeof v.property_id !== "string" || !v.property_id) issues.push({ index, field: "property_id", message: "can't be blank" });
    const hasDate = typeof v.date === "string" && isValidIsoDate(v.date);
    const hasRange = typeof v.date_from === "string" && typeof v.date_to === "string" && isValidIsoDate(v.date_from) && isValidIsoDate(v.date_to);
    if (!hasDate && !hasRange) issues.push({ index, field: "date", message: "date or date_from/date_to required (YYYY-MM-DD)" });
    if (hasRange && (v.date_from as string) > (v.date_to as string)) issues.push({ index, field: "date_from", message: "must be <= date_to" });
    if (path === "restrictions") {
      if (typeof v.rate_plan_id !== "string" || !v.rate_plan_id) issues.push({ index, field: "rate_plan_id", message: "can't be blank" });
      if (v.rate !== undefined) {
        const rate = Number(v.rate);
        if (!Number.isFinite(rate) || rate < 0) issues.push({ index, field: "rate", message: "must be a non-negative number" });
        else if (rate > 0 && rate < BOOKING_MIN_AMOUNT) warnings.push(`values[${index}].rate ${rate} is below ${BOOKING_MIN_AMOUNT}: OTAs may refuse it`);
      }
      if (v.rates !== undefined) {
        if (!Array.isArray(v.rates)) issues.push({ index, field: "rates", message: "must be an array of {occupancy, rate}" });
        else
          for (const r of v.rates) {
            if (!isRecord(r) || !(Number(r.occupancy) >= 1) || !Number.isFinite(Number(r.rate)) || Number(r.rate) < 0) {
              issues.push({ index, field: "rates", message: "each entry needs occupancy >= 1 and rate >= 0" });
              break;
            }
          }
      }
      for (const key of ["min_stay_arrival", "min_stay_through", "min_stay", "max_stay"]) {
        if (v[key] !== undefined && v[key] !== null && !(Number.isInteger(Number(v[key])) && Number(v[key]) >= 0)) {
          issues.push({ index, field: key, message: "must be a non-negative integer" });
        }
      }
      for (const key of ["closed_to_arrival", "closed_to_departure", "stop_sell"]) {
        if (v[key] !== undefined && typeof v[key] !== "boolean") issues.push({ index, field: key, message: "must be boolean" });
      }
      if (v.days !== undefined && !isRecord(v.days)) warnings.push(`values[${index}].days ignored: expected an object {mo..su: boolean}`);
    } else {
      if (typeof v.room_type_id !== "string" || !v.room_type_id) issues.push({ index, field: "room_type_id", message: "can't be blank" });
      const availability = Number(v.availability);
      if (!(Number.isInteger(availability) && availability >= 0)) issues.push({ index, field: "availability", message: "must be a non-negative integer" });
      else if (availability > 500) warnings.push(`values[${index}].availability ${availability} looks unusually high`);
    }
  });
  // Per-value findings: like Channex, the value is rejected from the update and
  // echoed back as a warning object (identifying fields + `warning`), while the
  // rest of the batch is applied — HTTP 200.
  const fieldsByIndex = new Map<number, Record<string, string[]>>();
  for (const i of issues) {
    const bucket = fieldsByIndex.get(i.index) ?? {};
    (bucket[i.field] ??= []).push(i.message);
    fieldsByIndex.set(i.index, bucket);
  }
  const rejected: AdapterRejection[] = [...fieldsByIndex.entries()]
    .sort((a, b) => a[0] - b[0])
    .map(([itemIndex, fields]) => {
      const [field, messages] = Object.entries(fields)[0] as [string, string[]];
      return { itemIndex, code: "validation_error", message: `${field}: ${messages[0] ?? ""}` };
    });
  const echo = (index: number): Record<string, unknown> => {
    const v = values[index];
    if (!isRecord(v)) return { index };
    const out: Record<string, unknown> = {};
    for (const key of ["property_id", "rate_plan_id", "room_type_id", "date", "date_from", "date_to"]) if (v[key] !== undefined) out[key] = v[key];
    return out;
  };
  const warningObjects: unknown[] = [
    ...[...fieldsByIndex.entries()].sort((a, b) => a[0] - b[0]).map(([index, fields]) => ({ ...echo(index), warning: fields })),
    ...warnings
  ];
  const allWarnings = [...rejected.map((r) => `values[${r.itemIndex}] rejected: ${r.message}`), ...warnings];
  return {
    status: 200,
    body: JSON.stringify({ data: [{ id: `sbx-task-${values.length}`, type: "task" }], meta: { message: "Success", warnings: warningObjects } }),
    accepted: values.length - rejected.length,
    rejected,
    errors: [],
    warnings: allWarnings
  };
}

// ---------------------------------------------------------------- Expedia EQC

function eqcRs(root: string, error: { code: string; message: string } | null, warnings: Array<{ code: string; message: string }> = []): string {
  const head = `<?xml version="1.0" encoding="UTF-8"?>\n<${root} xmlns="${EQC_AR_NS}">`;
  if (!error) {
    if (warnings.length === 0) return `${head}<Success/></${root}>`;
    // EQC: the update was applied; the warnings ride inside <Success>.
    return `${head}<Success>${warnings.map((w) => `<Warning code="${escapeXml(w.code)}">${escapeXml(w.message)}</Warning>`).join("")}</Success></${root}>`;
  }
  return `${head}<Error code="${escapeXml(error.code)}">${escapeXml(error.message)}</Error></${root}>`;
}

export function simulateExpediaEqc(xml: string, now: Date = new Date()): Omit<SimulatorResponse, "timedOut" | "contentType"> {
  const fail = (code: string, message: string, status = 200) => ({
    status,
    body: eqcRs("AvailRateUpdateRS", { code, message }),
    accepted: 0,
    rejected: [],
    errors: [message],
    warnings: [] as string[]
  });
  if (!/<AvailRateUpdateRQ\b/.test(xml)) return fail("3000", "Expected AvailRateUpdateRQ root element");
  if (!xml.includes(EQC_AR_NS)) return fail("3000", `Missing EQC AR namespace ${EQC_AR_NS}`);
  const auth = xmlElements(xml, "Authentication")[0];
  if (!auth) return fail("1001", "Authentication element is required");
  const username = xmlAttr(auth.tag, "username");
  const password = xmlAttr(auth.tag, "password");
  if (!username || !password) return fail("1001", "Authentication username/password are required");
  if (password === "INVALID") return fail("1001", "Authentication failed");
  const hotel = xmlElements(xml, "Hotel")[0];
  if (!hotel || !xmlAttr(hotel.tag, "id")) return fail("3000", "Hotel id is required");
  const updates = xmlElements(xml, "AvailRateUpdate");
  if (updates.length === 0) return fail("3000", "At least one AvailRateUpdate is required");
  const warnings: Array<{ code: string; message: string }> = [];
  for (const [i, u] of updates.entries()) {
    const range = xmlElements(u.inner, "DateRange")[0];
    const from = range ? xmlAttr(range.tag, "from") : null;
    const to = range ? xmlAttr(range.tag, "to") : null;
    if (!isValidIsoDate(from) || !isValidIsoDate(to)) return fail("3204", `AvailRateUpdate[${i}]: DateRange from/to must be valid dates`);
    if (from > to) return fail("3204", `AvailRateUpdate[${i}]: DateRange from must be <= to`);
    if (tooFarAhead(to, now)) return fail("3204", `AvailRateUpdate[${i}]: dates beyond ${MAX_YEARS_AHEAD} years are not accepted`);
    const rooms = xmlElements(u.inner, "RoomType");
    if (rooms.length === 0) return fail("3000", `AvailRateUpdate[${i}]: RoomType is required`);
    for (const room of rooms) {
      if (!xmlAttr(room.tag, "id")) return fail("3000", `AvailRateUpdate[${i}]: RoomType id is required`);
      const inv = xmlElements(room.inner, "Inventory")[0];
      if (inv) {
        const total = xmlAttr(inv.tag, "totalInventoryAvailable") ?? xmlAttr(inv.tag, "flexibleAllocation");
        if (total === null || !(Number.isInteger(Number(total)) && Number(total) >= 0)) return fail("3000", `AvailRateUpdate[${i}]: Inventory totalInventoryAvailable must be a non-negative integer`);
      }
      for (const plan of xmlElements(room.inner, "RatePlan")) {
        if (!xmlAttr(plan.tag, "id")) return fail("3000", `AvailRateUpdate[${i}]: RatePlan id is required`);
        for (const rate of xmlElements(plan.inner, "Rate")) {
          const currency = xmlAttr(rate.tag, "currency");
          if (!currency || currency.length !== 3) return fail("3202", `AvailRateUpdate[${i}]: Rate currency must be an ISO-4217 code`);
          const perDay = xmlElements(rate.inner, "PerDay");
          const perOcc = xmlElements(rate.inner, "PerOccupancy");
          if (perDay.length === 0 && perOcc.length === 0) return fail("3202", `AvailRateUpdate[${i}]: Rate needs PerDay or PerOccupancy`);
          for (const p of [...perDay, ...perOcc]) {
            const amount = Number(xmlAttr(p.tag, "rate"));
            if (!Number.isFinite(amount) || amount <= 0) return fail("3202", `AvailRateUpdate[${i}]: rate must be a positive number`);
            if (p.tag.startsWith("<PerOccupancy") && !(Number(xmlAttr(p.tag, "occupancy")) >= 1)) return fail("3202", `AvailRateUpdate[${i}]: PerOccupancy occupancy must be >= 1`);
            // Applied with a notice, like EQC's rate verification warnings.
            if (amount < BOOKING_MIN_AMOUNT) warnings.push({ code: "3260", message: `AvailRateUpdate[${i}]: rate ${amount} is below the usual minimum (${BOOKING_MIN_AMOUNT}); applied, please verify` });
          }
        }
        const restr = xmlElements(plan.inner, "Restrictions")[0];
        if (restr) {
          for (const key of ["minLOS", "maxLOS"]) {
            const v = xmlAttr(restr.tag, key);
            if (v !== null && !(Number.isInteger(Number(v)) && Number(v) >= 0)) return fail("3000", `AvailRateUpdate[${i}]: Restrictions ${key} must be a non-negative integer`);
          }
          for (const key of ["closedToArrival", "closedToDeparture"]) {
            const v = xmlAttr(restr.tag, key);
            if (v !== null && v !== "true" && v !== "false") return fail("3000", `AvailRateUpdate[${i}]: Restrictions ${key} must be true|false`);
          }
        }
      }
    }
  }
  return { status: 200, body: eqcRs("AvailRateUpdateRS", null, warnings), accepted: updates.length, rejected: [], errors: [], warnings: warnings.map((w) => `${w.code}: ${w.message}`) };
}

// ---------------------------------------------------------------- dispatcher

const requestCounters = new Map<string, number>();

/** Test hook: forget the per-channel request counters used by `failEvery`. */
export function resetSimulatorCounters(): void {
  requestCounters.clear();
}

function rateLimitedBody(provider: SimulatorProvider): { body: string; contentType: string } {
  if (provider === "channex") {
    return { body: JSON.stringify({ errors: { code: "too_many_requests", title: "Rate limit exceeded (simulated)" } }), contentType: "application/json" };
  }
  if (provider === "expedia") {
    return { body: eqcRs("AvailRateUpdateRS", { code: "4000", message: "Too many requests (simulated)" }), contentType: "text/xml" };
  }
  return { body: otaRs("OTA_ErrorRS", [{ code: "429", shortText: "Too many requests (simulated)" }], []), contentType: "text/xml" };
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Runs one simulated request. Applies the failure-injection knobs first (429
 * every N-th request, latency / timeout), then validates against the provider
 * schema. Never throws: a malformed body is a provider error response.
 */
export async function runSimulator(req: SimulatorRequest): Promise<SimulatorResponse> {
  const counterKey = `${req.channelId ?? "anon"}:${req.provider}`;
  const count = (requestCounters.get(counterKey) ?? 0) + 1;
  requestCounters.set(counterKey, count);
  const failEvery = req.options?.failEvery ?? 0;
  const latencyMs = req.options?.latencyMs ?? 0;
  const timeoutMs = req.timeoutMs ?? 30_000;
  const contentType = req.provider === "channex" ? "application/json" : "text/xml";

  if (latencyMs > 0 && latencyMs >= timeoutMs) {
    return { status: 0, body: "", contentType, timedOut: true, accepted: 0, rejected: [], errors: [`Simulated timeout after ${timeoutMs} ms`], warnings: [] };
  }
  if (latencyMs > 0) await sleep(Math.min(latencyMs, 5_000));

  if (failEvery > 0 && count % failEvery === 0) {
    const limited = rateLimitedBody(req.provider);
    return { status: 429, body: limited.body, contentType: limited.contentType, timedOut: false, accepted: 0, rejected: [], errors: ["Rate limited (simulated 429)"], warnings: [] };
  }

  const result =
    req.provider === "booking"
      ? simulateBookingOta(req.body)
      : req.provider === "channex"
        ? simulateChannex(req.endpoint, req.body)
        : simulateExpediaEqc(req.body);
  return { ...result, contentType, timedOut: false };
}
