import type { PermissionKey, RoleKey } from "./types.js";

export const PERMISSIONS: Record<PermissionKey, string> = {
  "pms.reservation.read": "Read reservations and arrivals",
  "pms.reservation.create": "Create reservations",
  "pms.reservation.modify": "Modify reservations",
  "pms.checkin.execute": "Execute guest check-in",
  "pms.checkout.execute": "Execute guest check-out",
  "folio.charge.post": "Post folio charges",
  "payment.capture": "Capture payments",
  "payment.refund": "Refund payments",
  "invoice.issue": "Issue invoices",
  "invoice.cancel": "Cancel or rectify invoices",
  "housekeeping.task.manage": "Manage housekeeping tasks",
  "maintenance.workorder.manage": "Manage maintenance work orders",
  "asset.capex.approve": "Approve capex",
  "accounting.journal.post": "Post accounting journals",
  "compliance.ses.submit": "Submit SES.HOSPEDAJES records",
  "compliance.ses.export": "Export SES.HOSPEDAJES batch files for manual upload",
  "compliance.ses.configure": "Configure SES.HOSPEDAJES credentials, schema templates and submission mode",
  "compliance.gdpr.manage": "Manage GDPR data subject requests, DSAR fulfillment, erasure and PII backfill",
  "guest_register.read": "Read Spain guest register records",
  "guest_register.create": "Create Spain guest register records",
  "guest_register.edit": "Edit Spain guest register records",
  "guest_register.sign": "Capture guest register signatures",
  "guest_register.submit": "Queue guest register records for authority submission",
  "guest_register.export": "Export guest register batches and evidence",
  "guest_register.annul": "Annul authority communications",
  "guest_register.correct": "Correct rejected guest register records",
  "guest_register.view_sensitive": "View sensitive guest register fields with audit logging",
  "guest_register.configure": "Configure guest register field, routing and retention settings",
  "ai.tool.execute": "Execute AI-backed tools",
  "ai.high_risk.confirm": "Confirm high-risk AI actions",
  "modules.read": "Read module catalog and enabled property modules",
  "modules.enable": "Enable property modules",
  "modules.disable": "Disable property modules",
  "integrations.read": "Read integration catalog and connections",
  "integrations.connect": "Connect integration providers",
  "integrations.disconnect": "Disconnect integration providers",
  "integrations.test": "Test integration connections",
  "integrations.manage_credentials": "Manage integration credential references",
  "distribution.read": "Read distribution hub data",
  "distribution.manage_rates": "Manage rates",
  "distribution.manage_inventory": "Manage inventory restrictions",
  "distribution.sync": "Run channel sync jobs",
  "distribution.ai_recommend": "View AI revenue recommendations",
  "payments.create_link": "Create payment links",
  "payments.capture": "Capture payments through payment vault",
  "payments.refund_request": "Request payment refunds",
  "payments.refund_approve": "Approve payment refunds",
  "billing.invoice.issue": "Issue compliance billing invoices",
  "billing.invoice.cancel": "Cancel compliance billing invoices",
  "billing.invoice.rectify": "Create rectifying invoices",
  "billing.compliance.view": "View invoice compliance status",
  "pos.order.create": "Create POS orders",
  "pos.order.charge_to_room": "Charge POS orders to rooms",
  "pos.order.pay": "Pay POS orders directly",
  "pos.product.manage": "Manage POS products",
  "guest_experience.inbox.read": "Read guest experience inbox",
  "guest_experience.message.send": "Send guest messages",
  "guest_experience.ai_reply": "Draft AI guest replies",
  "guest_experience.handoff": "Hand guest conversations to staff",
  "owner.dashboard.read": "Read owner dashboard",
  "owner.ai_ask": "Ask owner dashboard AI questions",
  "assets.read": "Read asset intelligence",
  "assets.manage": "Manage asset intelligence records",
  "capex.read": "Read capex projects",
  "capex.create": "Create capex projects",
  "capex.approve": "Approve capex projects",
  "backoffice.access": "Access the Back Office control panel",
  "property.configure": "Configure organization and property settings",
  "configuration.read": "Read property configuration center, categories and setup forms",
  "configuration.manage": "Manage property configuration center settings",
  "categories.read": "Read property category definitions and options",
  "categories.manage": "Create, edit, deactivate, reactivate and reorder category options",
  "categories.import": "Import category options from CSV, XLSX or JSON with preview",
  "categories.export": "Export property category options",
  "custom_fields.read": "Read custom field definitions and values",
  "custom_fields.manage": "Create, edit and deactivate custom fields",
  "property_profile.edit": "Edit property profile and business-date settings",
  "room_types.manage": "Manage room types and room type defaults",
  "rooms.manage": "Manage rooms and room setup forms",
  "spaces.manage": "Manage spaces and bookable resources",
  "departments.manage": "Manage departments",
  "operations_setup.manage": "Manage housekeeping, maintenance and operations setup categories",
  "revenue_setup.manage": "Manage revenue setup categories and segment taxonomies",
  "compliance_setup.manage": "Manage compliance setup categories and controlled legal values",
  "ai_category_setup.use": "Use AI setup assistant for category suggestions",
  "property.map.read": "Read property map, rooms, spaces, and assets",
  "property.map.manage": "Manage buildings, floors, zones, rooms, spaces, and map positions",
  "property.import": "Import property map data from CSV or XLSX",
  "property.go_live": "Approve property go-live",
  "modules.configure": "Configure enabled property modules",
  "integrations.configure": "Configure integration connections",
  "integrations.view_logs": "View integration event logs",
  "users.read": "Read staff and user assignments",
  "users.invite": "Invite users",
  "users.disable": "Disable users",
  "roles.manage": "Manage roles",
  "permissions.manage": "Manage permissions",
  "tax.configure": "Configure tax settings",
  "compliance.configure": "Configure compliance settings",
  "billing.configure": "Configure billing and invoice sequences",
  "accounting.configure": "Configure accounting settings",
  "payments.configure": "Configure payment providers and payment policy",
  "ai.configure": "Configure AI settings and tool automation",
  "templates.read": "Read document templates",
  "templates.manage": "Manage document templates",
  "revenue.read": "Read revenue and profit engine dashboards",
  "revenue.forecast.read": "Read revenue forecasts and forecast accuracy",
  "revenue.recommend": "Generate revenue recommendations",
  "revenue.manage_rates": "Manage revenue rates and restrictions",
  "revenue.manage_restrictions": "Manage revenue restrictions, stop sell, CTA, CTD and length-of-stay controls",
  "revenue.apply_recommendations": "Apply approved revenue recommendations",
  "revenue.automation.manage": "Manage revenue automation rules and safe auto-apply constraints",
  "revenue.configure": "Configure revenue engine rules",
  "revenue.history_forecast.read": "Read Revenue History & Forecast visual dashboards and report tables",
  "revenue.history_forecast.export": "Export Revenue History & Forecast reports to PDF, CSV, XLSX or JSON",
  "revenue.history_forecast.configure": "Configure Revenue History & Forecast defaults, visible KPIs and alert thresholds",
  "revenue.history_forecast.saved_views.manage": "Create and manage saved Revenue History & Forecast report views",
  "revenue.forecast_confidence.read": "Read forecast confidence bands, drivers and data quality signals",
  "revenue.comparison.read": "Compare revenue periods against previous period, last year or custom ranges",
  "revenue.visual_alerts.read": "Read visual revenue alerts for low demand, confidence, parity and sync risks",
  "revenue.scheduled_reports.manage": "Manage scheduled Revenue History & Forecast owner reports",
  "channel_manager.read": "Read channel manager dashboards, sync health and mapping status",
  "channel_manager.manage": "Manage channel connections",
  "channel_manager.sync": "Run channel manager ARI sync jobs",
  "channel_manager.mappings.manage": "Manage channel room and rate mappings",
  "channel_manager.parity.read": "Read channel rate parity alerts and parity monitoring",
  "guests.read": "Read guest profiles and stay history",
  "guests.manage": "Create and edit guest profiles",
  "crm.read": "Read CRM guest profiles",
  "crm.manage_profiles": "Manage CRM guest profiles",
  "crm.manage_campaigns": "Manage CRM campaigns",
  "crm.manage_loyalty": "Manage loyalty programs",
  "crm.export": "Export CRM profile and campaign data",
  "groups.read": "Read group bookings",
  "groups.manage": "Manage group bookings",
  "groups.block_inventory": "Block inventory for groups",
  "groups.manage_billing": "Manage group billing",
  "events.read": "Read events and function diary",
  "events.manage": "Manage events",
  "events.manage_spaces": "Manage event spaces",
  "sales.pipeline.read": "Read sales pipeline",
  "sales.pipeline.manage": "Manage sales pipeline",
  "workforce.read": "Read workforce schedules",
  "workforce.schedule.manage": "Manage staff schedules",
  "workforce.timeclock.use": "Use staff time clock",
  "workforce.timeclock.manage": "Manage time clock records",
  "workforce.labor_cost.view": "View labor cost dashboards",
  "workforce.payroll_export": "Export payroll data",
  "payroll.manage": "Manage payroll contracts, periods and payroll calculation runs",
  "banking.reconcile": "Manage bank accounts, statement imports and reconciliation matching",
  "notifications.manage": "Manage notification templates, dispatch and delivery retries",
  "procurement.read": "Read procurement records",
  "procurement.manage": "Manage procurement records",
  "purchase_orders.create": "Create purchase orders",
  "purchase_orders.approve": "Approve purchase orders",
  "purchase_orders.receive": "Receive purchase orders",
  "inventory.read": "Read inventory stock",
  "inventory.manage": "Manage inventory items and locations",
  "inventory.stock_count": "Perform stock counts",
  "inventory.adjust": "Adjust inventory stock",
  "guest_portal.configure": "Configure guest portal",
  "guest_self_service.read": "Read guest self-service status",
  "guest_self_service.manage": "Manage guest self-service actions",
  "kiosk.configure": "Configure kiosk flows",
  "digital_key.configure": "Configure digital key adapters",
  "reputation.read": "Read reputation dashboards",
  "reputation.respond": "Respond to guest reviews",
  "surveys.read": "Read surveys and responses",
  "surveys.manage": "Manage surveys",
  "quality_cases.read": "Read quality cases",
  "quality_cases.manage": "Manage quality cases",
  "energy.read": "Read energy dashboards",
  "energy.manage": "Manage utility meters and readings",
  "sustainability.read": "Read sustainability dashboards",
  "sustainability.report": "Generate sustainability reports",
  "iot.manage": "Manage IoT and smart meter integrations",
  "incidents.read": "Read safety incidents",
  "incidents.manage": "Manage safety incidents",
  "safety_checks.read": "Read safety checks",
  "safety_checks.manage": "Manage safety checks",
  "insurance_cases.manage": "Manage insurance cases",
  "analytics.read": "Read analytics dashboards",
  "analytics.configure": "Configure analytics platform",
  "analytics.export": "Export analytics data",
  "analytics.ai_ask": "Ask analytics AI questions",
  "metrics.manage": "Manage semantic metrics",
  "developer.read": "Read developer platform",
  "developer.manage_apps": "Manage developer apps",
  "developer.manage_webhooks": "Manage webhooks",
  "developer.view_api_logs": "View API usage logs",
  "developer.manage_sandbox": "Manage developer sandbox",
  "ai_governance.read": "Read AI governance center",
  "ai_governance.configure": "Configure AI governance policies",
  "ai_evals.manage": "Manage AI evaluations",
  "ai_incidents.read": "Read AI incidents",
  "ai_incidents.manage": "Manage AI incidents",
  "ai_prompts.manage": "Manage AI prompt versions",
  "ai_tool_registry.manage": "Manage AI tool registry",
  "onboarding.read": "Read AI onboarding and migration projects",
  "onboarding.create": "Create AI onboarding projects",
  "onboarding.upload": "Upload onboarding source files and exports",
  "onboarding.connect_source": "Connect source PMS systems for migration",
  "onboarding.ai_extract": "Run AI document extraction for onboarding",
  "onboarding.ai_map": "Run AI schema mapping for onboarding",
  "onboarding.review": "Review, approve, edit or reject onboarding mappings",
  "onboarding.apply": "Apply approved migration batches",
  "onboarding.rollback": "Rollback eligible migration batches",
  "onboarding.go_live": "Approve onboarding go-live readiness",
  "onboarding.view_sensitive": "View sensitive onboarding previews and source records",
  "onboarding.manage_cutover": "Manage cutover plan, freeze window and delta import",
  "audit.read": "Read audit logs"
};

export const ROLE_PERMISSION_MAP: Record<RoleKey, PermissionKey[]> = {
  owner: [
    "pms.reservation.read",
    "guests.read",
    "invoice.issue",
    "invoice.cancel",
    "asset.capex.approve",
    "assets.read",
    "capex.read",
    "capex.approve",
    "accounting.journal.post",
    "ai.tool.execute",
    "ai.high_risk.confirm",
    "modules.read",
    "integrations.read",
    "owner.dashboard.read",
    "owner.ai_ask",
    "backoffice.access",
    "property.map.read",
    "audit.read"
  ],
  manager: [
    "pms.reservation.read",
    "pms.reservation.create",
    "pms.reservation.modify",
    "pms.checkin.execute",
    "pms.checkout.execute",
    "folio.charge.post",
    "guests.read",
    "guests.manage",
    "payment.capture",
    "payment.refund",
    "invoice.issue",
    "invoice.cancel",
    "housekeeping.task.manage",
    "maintenance.workorder.manage",
    "compliance.ses.submit",
    "compliance.ses.export",
    "compliance.ses.configure",
    "guest_register.read",
    "guest_register.create",
    "guest_register.edit",
    "guest_register.sign",
    "guest_register.submit",
    "guest_register.export",
    "guest_register.annul",
    "guest_register.correct",
    "guest_register.view_sensitive",
    "guest_register.configure",
    "modules.read",
    "modules.enable",
    "modules.disable",
    "integrations.read",
    "integrations.connect",
    "integrations.disconnect",
    "integrations.test",
    "distribution.read",
    "distribution.manage_rates",
    "distribution.manage_inventory",
    "distribution.sync",
    "payments.create_link",
    "payments.capture",
    "payments.refund_request",
    "payments.refund_approve",
    "billing.invoice.issue",
    "billing.invoice.cancel",
    "billing.invoice.rectify",
    "billing.compliance.view",
    "pos.order.create",
    "pos.order.charge_to_room",
    "pos.order.pay",
    "guest_experience.inbox.read",
    "guest_experience.message.send",
    "guest_experience.ai_reply",
    "guest_experience.handoff",
    "assets.read",
    "assets.manage",
    "capex.read",
    "capex.create",
    "ai.tool.execute",
    "ai.high_risk.confirm",
    "backoffice.access",
    "property.configure",
    "property.map.read",
    "property.map.manage",
    "property.import",
    "property.go_live",
    "modules.configure",
    "integrations.configure",
    "integrations.view_logs",
    "users.read",
    "users.invite",
    "users.disable",
    "roles.manage",
    "tax.configure",
    "compliance.configure",
    "billing.configure",
    "accounting.configure",
    "payments.configure",
    "ai.configure",
    "templates.read",
    "templates.manage",
    "channel_manager.parity.read",
    "payroll.manage",
    "banking.reconcile",
    "notifications.manage",
    "audit.read"
  ],
  receptionist: [
    "pms.reservation.read",
    "pms.reservation.create",
    "pms.reservation.modify",
    "pms.checkin.execute",
    "pms.checkout.execute",
    "folio.charge.post",
    "payment.capture",
    "payments.create_link",
    "guests.read",
    "guests.manage",
    "guest_register.read",
    "guest_register.create",
    "guest_register.edit",
    "guest_register.sign",
    "guest_register.submit",
    "guest_experience.inbox.read",
    "guest_experience.message.send",
    "ai.tool.execute"
  ],
  housekeeper: ["housekeeping.task.manage", "ai.tool.execute"],
  maintenance: ["maintenance.workorder.manage", "ai.tool.execute"],
  accountant: [
    "pms.reservation.read",
    "invoice.issue",
    "invoice.cancel",
    "accounting.journal.post",
    "accounting.configure",
    "billing.configure",
    "audit.read",
    "ai.tool.execute",
    "ai.high_risk.confirm"
  ],
  compliance: [
    "pms.reservation.read",
    "compliance.ses.submit",
    "compliance.ses.export",
    "compliance.ses.configure",
    "guest_register.read",
    "guest_register.create",
    "guest_register.edit",
    "guest_register.sign",
    "guest_register.submit",
    "guest_register.export",
    "guest_register.annul",
    "guest_register.correct",
    "guest_register.view_sensitive",
    "guest_register.configure",
    "compliance.configure",
    "tax.configure",
    "audit.read",
    "ai.tool.execute",
    "ai.high_risk.confirm"
  ],
  admin: Object.keys(PERMISSIONS) as PermissionKey[]
};

export function hasPermission(userPermissions: PermissionKey[], permission: PermissionKey): boolean {
  return userPermissions.includes(permission);
}

export function missingPermissions(userPermissions: PermissionKey[], required: PermissionKey[]): PermissionKey[] {
  return required.filter((permission) => !hasPermission(userPermissions, permission));
}

export function assertPermissions(userPermissions: PermissionKey[], required: PermissionKey[]): void {
  const missing = missingPermissions(userPermissions, required);
  if (missing.length > 0) {
    throw new Error(`Missing permissions: ${missing.join(", ")}`);
  }
}
